modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "biologydictionary"
version = "${version}"
displayName = "Biology Dictionary"
authors = "XieNaoban"
description = '''
To display or modify the properties and states of mobs.
'''
#logoFile = ""

[[dependencies.biologydictionary]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biologydictionary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biologydictionary]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
