# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# IntelliJ IDEA is not yet fully compatible with Loom configuration cache.
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
java_version=25

# Fabric
loom_version=1.16-SNAPSHOT
loader_version=0.19.3
fabricapi_version=0.151.0+26.1.2
modmenu_version=18.0.0-beta.1

# NeoForge
moddev_version=2.0.141
neoforge_version=26.1.2.75

# Dependencies
clothconfig_version=26.1.154
snakeyaml_version=2.2

# Dependencies (Test Only)
javaparser_version=3.28.2
procyon_version=0.6.0
vineflower_version=1.10.1

# Mod
mod_id=biologydictionary
mod_name=Biology Dictionary
mod_license=LGPL-3.0
mod_version=1.1.0
maven_group=io.github.xienaoban.biologydictionary
