# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6
loader_version=0.16.14
# Mod Properties
mod_version=0.2.1
maven_group=io.github.xienaoban.minecraft
archives_base_name=biologydictionary

# Dependencies
# check these on https://fabricmc.net/develop
fabric_version=0.127.1+1.21.6

javaparser_version=3.26.3
procyon_version=0.6.0
fernflower_version=6.3.9.Final
vineflower_version=1.10.1
