package io.github.xienaoban.minecraft.biologydictionary.core.property;

import io.github.xienaoban.minecraft.biologydictionary.api.EntityVanillaProperty;
import io.github.xienaoban.minecraft.biologydictionary.core.property.preset.*;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;

@Environment(EnvType.CLIENT)
public final class EntityVanillaProperties {

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Air": SHORT
     *  - "CustomName": STRING
     *  - "CustomNameVisible": BOOLEAN
     *  - "FallDistance": FLOAT
     *  - "Fire": SHORT
     *  - "Glowing": BOOLEAN
     *  - "HasVisualFire": BOOLEAN
     *  - "Invulnerable": BOOLEAN
     *  - "Motion": [DOUBLE]
     *  - "NoGravity": BOOLEAN
     *  - "OnGround": BOOLEAN
     *  - "PortalCooldown": INT
     *  - "Pos": [DOUBLE]
     *  - "Rotation": [FLOAT]
     *  - "Silent": BOOLEAN
     *  - "Tags": [STRING]
     *  - "TicksFrozen": INT
     *  - "UUID": UUID
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Passengers": [ANY] - "id": [STRING]
     * @see net.minecraft.world.entity.Entity
     */
    public static final class OfEntity {

        public static ShortProperty generateAirProperty() {
            return new ShortProperty("Air");
        }

        public static StringProperty generateCustomNameProperty() {
            return new StringProperty("CustomName");
        }

        public static BooleanProperty generateCustomNameVisibleProperty() {
            return new BooleanProperty("CustomNameVisible");
        }

        public static FloatProperty generateFallDistanceProperty() {
            return new FloatProperty("FallDistance");
        }

        public static ShortProperty generateFireProperty() {
            return new ShortProperty("Fire");
        }

        public static BooleanProperty generateGlowingProperty() {
            return new BooleanProperty("Glowing");
        }

        public static BooleanProperty generateHasVisualFireProperty() {
            return new BooleanProperty("HasVisualFire");
        }

        public static BooleanProperty generateInvulnerableProperty() {
            return new BooleanProperty("Invulnerable");
        }

        public static DoubleListProperty generateMotionProperty() {
            return new DoubleListProperty("Motion");
        }

        public static BooleanProperty generateNoGravityProperty() {
            return new BooleanProperty("NoGravity");
        }

        public static BooleanProperty generateOnGroundProperty() {
            return new BooleanProperty("OnGround");
        }

        public static IntProperty generatePortalCooldownProperty() {
            return new IntProperty("PortalCooldown");
        }

        public static DoubleListProperty generatePosProperty() {
            return new DoubleListProperty("Pos");
        }

        public static FloatListProperty generateRotationProperty() {
            return new FloatListProperty("Rotation");
        }

        public static BooleanProperty generateSilentProperty() {
            return new BooleanProperty("Silent");
        }

        public static StringListProperty generateTagsProperty() {
            return new StringListProperty("Tags");
        }

        public static IntProperty generateTicksFrozenProperty() {
            return new IntProperty("TicksFrozen");
        }

        public static UuidProperty generateUuidProperty() {
            return new UuidProperty("UUID");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "AbsorptionAmount": FLOAT
     *  - "DeathTime": SHORT
     *  - "FallFlying": BOOLEAN
     *  - "Health": FLOAT
     *  - "HurtByTimestamp": INT
     *  - "HurtTime": SHORT
     *  - "SleepingX": INT
     *  - "SleepingY": INT
     *  - "SleepingZ": INT
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Brain": [COMPOUND] - "Team": [STRING] - "active_effects": [[COMPOUND]] - "attributes": [[COMPOUND]]
     * @see net.minecraft.world.entity.LivingEntity
     */
    public static final class OfLivingEntity {

        public static FloatProperty generateAbsorptionAmountProperty() {
            return new FloatProperty("AbsorptionAmount");
        }

        public static ShortProperty generateDeathTimeProperty() {
            return new ShortProperty("DeathTime");
        }

        public static BooleanProperty generateFallFlyingProperty() {
            return new BooleanProperty("FallFlying");
        }

        public static FloatProperty generateHealthProperty() {
            return new FloatProperty("Health");
        }

        public static IntProperty generateHurtByTimestampProperty() {
            return new IntProperty("HurtByTimestamp");
        }

        public static ShortProperty generateHurtTimeProperty() {
            return new ShortProperty("HurtTime");
        }

        public static IntProperty generateSleepingXProperty() {
            return new IntProperty("SleepingX");
        }

        public static IntProperty generateSleepingYProperty() {
            return new IntProperty("SleepingY");
        }

        public static IntProperty generateSleepingZProperty() {
            return new IntProperty("SleepingZ");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "ArmorDropChances": [FLOAT]
     *  - "CanPickUpLoot": BOOLEAN
     *  - "DeathLootTable": STRING
     *  - "DeathLootTableSeed": LONG
     *  - "HandDropChances": [FLOAT]
     *  - "LeftHanded": BOOLEAN
     *  - "NoAI": BOOLEAN
     *  - "PersistenceRequired": BOOLEAN
     *  - "body_armor_drop_chance": FLOAT
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "ArmorItems": [[COMPOUND]] - "HandItems": [[COMPOUND]] - "body_armor_item": [COMPOUND]
     * @see net.minecraft.world.entity.Mob
     */
    public static final class OfMob {

        public static FloatListProperty generateArmorDropChancesProperty() {
            return new FloatListProperty("ArmorDropChances");
        }

        public static BooleanProperty generateCanPickUpLootProperty() {
            return new BooleanProperty("CanPickUpLoot");
        }

        public static StringProperty generateDeathLootTableProperty() {
            return new StringProperty("DeathLootTable");
        }

        public static LongProperty generateDeathLootTableSeedProperty() {
            return new LongProperty("DeathLootTableSeed");
        }

        public static FloatListProperty generateHandDropChancesProperty() {
            return new FloatListProperty("HandDropChances");
        }

        public static BooleanProperty generateLeftHandedProperty() {
            return new BooleanProperty("LeftHanded");
        }

        public static BooleanProperty generateNoAiProperty() {
            return new BooleanProperty("NoAI");
        }

        public static BooleanProperty generatePersistenceRequiredProperty() {
            return new BooleanProperty("PersistenceRequired");
        }

        public static FloatProperty generateBodyArmorDropChanceProperty() {
            return new FloatProperty("body_armor_drop_chance");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.FlyingMob
     */
    public static final class OfFlyingMob {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "ExplosionPower": BYTE
     *
     * @see net.minecraft.world.entity.monster.Ghast
     */
    public static final class OfGhast {

        public static ByteProperty generateExplosionPowerProperty() {
            return new ByteProperty("ExplosionPower");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "AX": INT
     *  - "AY": INT
     *  - "AZ": INT
     *  - "Size": INT
     *
     * @see net.minecraft.world.entity.monster.Phantom
     */
    public static final class OfPhantom {

        public static IntProperty generateAxProperty() {
            return new IntProperty("AX");
        }

        public static IntProperty generateAyProperty() {
            return new IntProperty("AY");
        }

        public static IntProperty generateAzProperty() {
            return new IntProperty("AZ");
        }

        public static IntProperty generateSizeProperty() {
            return new IntProperty("Size");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.PathfinderMob
     */
    public static final class OfPathfinderMob {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Age": INT
     *  - "ForcedAge": INT
     *
     * @see net.minecraft.world.entity.AgeableMob
     */
    public static final class OfAgeableMob {

        public static IntProperty generateAgeProperty() {
            return new IntProperty("Age");
        }

        public static IntProperty generateForcedAgeProperty() {
            return new IntProperty("ForcedAge");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.AgeableWaterCreature
     */
    public static final class OfAgeableWaterCreature {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "GotFish": BOOLEAN
     *  - "Moistness": INT
     *  - "TreasurePosX": INT
     *  - "TreasurePosY": INT
     *  - "TreasurePosZ": INT
     *
     * @see net.minecraft.world.entity.animal.Dolphin
     */
    public static final class OfDolphin {

        public static BooleanProperty generateGotFishProperty() {
            return new BooleanProperty("GotFish");
        }

        public static IntProperty generateMoistnessProperty() {
            return new IntProperty("Moistness");
        }

        public static IntProperty generateTreasurePosXProperty() {
            return new IntProperty("TreasurePosX");
        }

        public static IntProperty generateTreasurePosYProperty() {
            return new IntProperty("TreasurePosY");
        }

        public static IntProperty generateTreasurePosZProperty() {
            return new IntProperty("TreasurePosZ");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Squid
     */
    public static final class OfSquid {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "DarkTicksRemaining": INT
     *
     * @see net.minecraft.world.entity.GlowSquid
     */
    public static final class OfGlowSquid {

        public static IntProperty generateDarkTicksRemainingProperty() {
            return new IntProperty("DarkTicksRemaining");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "InLove": INT
     *  - "LoveCause": UUID
     *
     * @see net.minecraft.world.entity.animal.Animal
     */
    public static final class OfAnimal {

        public static IntProperty generateInLoveProperty() {
            return new IntProperty("InLove");
        }

        public static UuidProperty generateLoveCauseProperty() {
            return new UuidProperty("LoveCause");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Sitting": BOOLEAN
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Owner": [STRING, UUID]
     * @see net.minecraft.world.entity.TamableAnimal
     */
    public static final class OfTamableAnimal {

        public static BooleanProperty generateSittingProperty() {
            return new BooleanProperty("Sitting");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CollarColor": BYTE
     *  - "variant": STRING
     *
     * @see net.minecraft.world.entity.animal.Cat
     */
    public static final class OfCat {

        public static ByteProperty generateCollarColorProperty() {
            return new ByteProperty("CollarColor");
        }

        public static StringProperty generateVariantProperty() {
            return new StringProperty("variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "id": [STRING]
     * @see net.minecraft.world.entity.animal.ShoulderRidingEntity
     */
    public static final class OfShoulderRidingEntity {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.Parrot
     */
    public static final class OfParrot {

        public static IntProperty generateVariantProperty() {
            return new IntProperty("Variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CollarColor": BYTE
     *  - "variant": STRING
     *
     * @see net.minecraft.world.entity.animal.Wolf
     */
    public static final class OfWolf {

        public static ByteProperty generateCollarColorProperty() {
            return new ByteProperty("CollarColor");
        }

        public static StringProperty generateVariantProperty() {
            return new StringProperty("variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CannotEnterHiveTicks": INT
     *  - "CropsGrownSincePollination": INT
     *  - "HasNectar": BOOLEAN
     *  - "HasStung": BOOLEAN
     *  - "TicksSincePollination": INT
     *  - "flower_pos": BLOCK_POS
     *  - "hive_pos": BLOCK_POS
     *
     * @see net.minecraft.world.entity.animal.Bee
     */
    public static final class OfBee {

        public static IntProperty generateCannotEnterHiveTicksProperty() {
            return new IntProperty("CannotEnterHiveTicks");
        }

        public static IntProperty generateCropsGrownSincePollinationProperty() {
            return new IntProperty("CropsGrownSincePollination");
        }

        public static BooleanProperty generateHasNectarProperty() {
            return new BooleanProperty("HasNectar");
        }

        public static BooleanProperty generateHasStungProperty() {
            return new BooleanProperty("HasStung");
        }

        public static IntProperty generateTicksSincePollinationProperty() {
            return new IntProperty("TicksSincePollination");
        }

        public static BlockPosProperty generateFlowerPosProperty() {
            return new BlockPosProperty("flower_pos");
        }

        public static BlockPosProperty generateHivePosProperty() {
            return new BlockPosProperty("hive_pos");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "EggLayTime": INT
     *  - "IsChickenJockey": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.Chicken
     */
    public static final class OfChicken {

        public static IntProperty generateEggLayTimeProperty() {
            return new IntProperty("EggLayTime");
        }

        public static BooleanProperty generateIsChickenJockeyProperty() {
            return new BooleanProperty("IsChickenJockey");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Cow
     */
    public static final class OfCow {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Type": STRING
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "stew_effects": [[ANY]]
     * @see net.minecraft.world.entity.animal.MushroomCow
     */
    public static final class OfMushroomCow {

        public static StringProperty generateTypeProperty() {
            return new StringProperty("Type");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Crouching": BOOLEAN
     *  - "Sitting": BOOLEAN
     *  - "Sleeping": BOOLEAN
     *  - "Trusted": [INT_ARRAY]
     *  - "Type": STRING
     *
     * @see net.minecraft.world.entity.animal.Fox
     */
    public static final class OfFox {

        public static BooleanProperty generateCrouchingProperty() {
            return new BooleanProperty("Crouching");
        }

        public static BooleanProperty generateSittingProperty() {
            return new BooleanProperty("Sitting");
        }

        public static BooleanProperty generateSleepingProperty() {
            return new BooleanProperty("Sleeping");
        }

        public static EntityVanillaProperty generateTrustedProperty() {
            return null;
        }

        public static StringProperty generateTypeProperty() {
            return new StringProperty("Type");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Trusting": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.Ocelot
     */
    public static final class OfOcelot {

        public static BooleanProperty generateTrustingProperty() {
            return new BooleanProperty("Trusting");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "HiddenGene": STRING
     *  - "MainGene": STRING
     *
     * @see net.minecraft.world.entity.animal.Panda
     */
    public static final class OfPanda {

        public static StringProperty generateHiddenGeneProperty() {
            return new StringProperty("HiddenGene");
        }

        public static StringProperty generateMainGeneProperty() {
            return new StringProperty("MainGene");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Pig
     */
    public static final class OfPig {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.PolarBear
     */
    public static final class OfPolarBear {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "MoreCarrotTicks": INT
     *  - "RabbitType": INT
     *
     * @see net.minecraft.world.entity.animal.Rabbit
     */
    public static final class OfRabbit {

        public static IntProperty generateMoreCarrotTicksProperty() {
            return new IntProperty("MoreCarrotTicks");
        }

        public static IntProperty generateRabbitTypeProperty() {
            return new IntProperty("RabbitType");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Color": BYTE
     *  - "Sheared": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.Sheep
     */
    public static final class OfSheep {

        public static ByteProperty generateColorProperty() {
            return new ByteProperty("Color");
        }

        public static BooleanProperty generateShearedProperty() {
            return new BooleanProperty("Sheared");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "HasEgg": BOOLEAN
     *  - "HomePosX": INT
     *  - "HomePosY": INT
     *  - "HomePosZ": INT
     *  - "TravelPosX": INT
     *  - "TravelPosY": INT
     *  - "TravelPosZ": INT
     *
     * @see net.minecraft.world.entity.animal.Turtle
     */
    public static final class OfTurtle {

        public static BooleanProperty generateHasEggProperty() {
            return new BooleanProperty("HasEgg");
        }

        public static IntProperty generateHomePosXProperty() {
            return new IntProperty("HomePosX");
        }

        public static IntProperty generateHomePosYProperty() {
            return new IntProperty("HomePosY");
        }

        public static IntProperty generateHomePosZProperty() {
            return new IntProperty("HomePosZ");
        }

        public static IntProperty generateTravelPosXProperty() {
            return new IntProperty("TravelPosX");
        }

        public static IntProperty generateTravelPosYProperty() {
            return new IntProperty("TravelPosY");
        }

        public static IntProperty generateTravelPosZProperty() {
            return new IntProperty("TravelPosZ");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "scute_time": INT
     *  - "state": STRING
     *
     * @see net.minecraft.world.entity.animal.armadillo.Armadillo
     */
    public static final class OfArmadillo {

        public static IntProperty generateScuteTimeProperty() {
            return new IntProperty("scute_time");
        }

        public static StringProperty generateStateProperty() {
            return new StringProperty("state");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Age": INT
     *  - "FromBucket": BOOLEAN
     *  - "HuntingCooldown": LONG
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.axolotl.Axolotl
     */
    public static final class OfAxolotl {

        public static IntProperty generateAgeProperty() {
            return new IntProperty("Age");
        }

        public static BooleanProperty generateFromBucketProperty() {
            return new BooleanProperty("FromBucket");
        }

        public static LongProperty generateHuntingCooldownProperty() {
            return new LongProperty("HuntingCooldown");
        }

        public static IntProperty generateVariantProperty() {
            return new IntProperty("Variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "variant": STRING
     *
     * @see net.minecraft.world.entity.animal.frog.Frog
     */
    public static final class OfFrog {

        public static StringProperty generateVariantProperty() {
            return new StringProperty("variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "HasLeftHorn": BOOLEAN
     *  - "HasRightHorn": BOOLEAN
     *  - "IsScreamingGoat": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.goat.Goat
     */
    public static final class OfGoat {

        public static BooleanProperty generateHasLeftHornProperty() {
            return new BooleanProperty("HasLeftHorn");
        }

        public static BooleanProperty generateHasRightHornProperty() {
            return new BooleanProperty("HasRightHorn");
        }

        public static BooleanProperty generateIsScreamingGoatProperty() {
            return new BooleanProperty("IsScreamingGoat");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Bred": BOOLEAN
     *  - "EatingHaystack": BOOLEAN
     *  - "Tame": BOOLEAN
     *  - "Temper": INT
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Owner": [STRING, UUID] - "SaddleItem": [COMPOUND]
     * @see net.minecraft.world.entity.animal.horse.AbstractHorse
     */
    public static final class OfAbstractHorse {

        public static BooleanProperty generateBredProperty() {
            return new BooleanProperty("Bred");
        }

        public static BooleanProperty generateEatingHaystackProperty() {
            return new BooleanProperty("EatingHaystack");
        }

        public static BooleanProperty generateTameProperty() {
            return new BooleanProperty("Tame");
        }

        public static IntProperty generateTemperProperty() {
            return new IntProperty("Temper");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "LastPoseTick": LONG
     *
     * @see net.minecraft.world.entity.animal.camel.Camel
     */
    public static final class OfCamel {

        public static LongProperty generateLastPoseTickProperty() {
            return new LongProperty("LastPoseTick");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "ChestedHorse": BOOLEAN
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Items": [[COMPOUND]]
     * @see net.minecraft.world.entity.animal.horse.AbstractChestedHorse
     */
    public static final class OfAbstractChestedHorse {

        public static BooleanProperty generateChestedHorseProperty() {
            return new BooleanProperty("ChestedHorse");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.horse.Donkey
     */
    public static final class OfDonkey {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Strength": INT
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.horse.Llama
     */
    public static final class OfLlama {

        public static IntProperty generateStrengthProperty() {
            return new IntProperty("Strength");
        }

        public static IntProperty generateVariantProperty() {
            return new IntProperty("Variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "DespawnDelay": INT
     *
     * @see net.minecraft.world.entity.animal.horse.TraderLlama
     */
    public static final class OfTraderLlama {

        public static IntProperty generateDespawnDelayProperty() {
            return new IntProperty("DespawnDelay");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.horse.Mule
     */
    public static final class OfMule {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.horse.Horse
     */
    public static final class OfHorse {

        public static IntProperty generateVariantProperty() {
            return new IntProperty("Variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "SkeletonTrap": BOOLEAN
     *  - "SkeletonTrapTime": INT
     *
     * @see net.minecraft.world.entity.animal.horse.SkeletonHorse
     */
    public static final class OfSkeletonHorse {

        public static BooleanProperty generateSkeletonTrapProperty() {
            return new BooleanProperty("SkeletonTrap");
        }

        public static IntProperty generateSkeletonTrapTimeProperty() {
            return new IntProperty("SkeletonTrapTime");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.horse.ZombieHorse
     */
    public static final class OfZombieHorse {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.sniffer.Sniffer
     */
    public static final class OfSniffer {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Strider
     */
    public static final class OfStrider {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CannotBeHunted": BOOLEAN
     *  - "IsImmuneToZombification": BOOLEAN
     *  - "TimeInOverworld": INT
     *
     * @see net.minecraft.world.entity.monster.hoglin.Hoglin
     */
    public static final class OfHoglin {

        public static BooleanProperty generateCannotBeHuntedProperty() {
            return new BooleanProperty("CannotBeHunted");
        }

        public static BooleanProperty generateIsImmuneToZombificationProperty() {
            return new BooleanProperty("IsImmuneToZombification");
        }

        public static IntProperty generateTimeInOverworldProperty() {
            return new IntProperty("TimeInOverworld");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Offers": [ANY]
     * @see net.minecraft.world.entity.npc.AbstractVillager
     */
    public static final class OfAbstractVillager {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "AssignProfessionWhenSpawned": BOOLEAN
     *  - "FoodLevel": BYTE
     *  - "LastGossipDecay": LONG
     *  - "LastRestock": LONG
     *  - "RestocksToday": INT
     *  - "Xp": INT
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Gossips": [[COMPOUND]] - "VillagerData": [COMPOUND]
     * @see net.minecraft.world.entity.npc.Villager
     */
    public static final class OfVillager {

        public static BooleanProperty generateAssignProfessionWhenSpawnedProperty() {
            return new BooleanProperty("AssignProfessionWhenSpawned");
        }

        public static ByteProperty generateFoodLevelProperty() {
            return new ByteProperty("FoodLevel");
        }

        public static LongProperty generateLastGossipDecayProperty() {
            return new LongProperty("LastGossipDecay");
        }

        public static LongProperty generateLastRestockProperty() {
            return new LongProperty("LastRestock");
        }

        public static IntProperty generateRestocksTodayProperty() {
            return new IntProperty("RestocksToday");
        }

        public static IntProperty generateXpProperty() {
            return new IntProperty("Xp");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "DespawnDelay": INT
     *  - "wander_target": BLOCK_POS
     *
     * @see net.minecraft.world.entity.npc.WanderingTrader
     */
    public static final class OfWanderingTrader {

        public static IntProperty generateDespawnDelayProperty() {
            return new IntProperty("DespawnDelay");
        }

        public static BlockPosProperty generateWanderTargetProperty() {
            return new BlockPosProperty("wander_target");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.AbstractGolem
     */
    public static final class OfAbstractGolem {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "PlayerCreated": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.IronGolem
     */
    public static final class OfIronGolem {

        public static BooleanProperty generatePlayerCreatedProperty() {
            return new BooleanProperty("PlayerCreated");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Pumpkin": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.SnowGolem
     */
    public static final class OfSnowGolem {

        public static BooleanProperty generatePumpkinProperty() {
            return new BooleanProperty("Pumpkin");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "AttachFace": BYTE
     *  - "Color": BYTE
     *  - "Peek": BYTE
     *
     * @see net.minecraft.world.entity.monster.Shulker
     */
    public static final class OfShulker {

        public static ByteProperty generateAttachFaceProperty() {
            return new ByteProperty("AttachFace");
        }

        public static ByteProperty generateColorProperty() {
            return new ByteProperty("Color");
        }

        public static ByteProperty generatePeekProperty() {
            return new ByteProperty("Peek");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.WaterAnimal
     */
    public static final class OfWaterAnimal {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "FromBucket": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.AbstractFish
     */
    public static final class OfAbstractFish {

        public static BooleanProperty generateFromBucketProperty() {
            return new BooleanProperty("FromBucket");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.AbstractSchoolingFish
     */
    public static final class OfAbstractSchoolingFish {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Cod
     */
    public static final class OfCod {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "type": STRING
     *
     * @see net.minecraft.world.entity.animal.Salmon
     */
    public static final class OfSalmon {

        public static StringProperty generateTypeProperty() {
            return new StringProperty("type");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "BucketVariantTag": INT
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.TropicalFish
     */
    public static final class OfTropicalFish {

        public static IntProperty generateBucketVariantTagProperty() {
            return new IntProperty("BucketVariantTag");
        }

        public static IntProperty generateVariantProperty() {
            return new IntProperty("Variant");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "PuffState": INT
     *
     * @see net.minecraft.world.entity.animal.Pufferfish
     */
    public static final class OfPufferfish {

        public static IntProperty generatePuffStateProperty() {
            return new IntProperty("PuffState");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Age": INT
     *
     * @see net.minecraft.world.entity.animal.frog.Tadpole
     */
    public static final class OfTadpole {

        public static IntProperty generateAgeProperty() {
            return new IntProperty("Age");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CanDuplicate": BOOLEAN
     *  - "DuplicationCooldown": INT
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "listener": [COMPOUND]
     * @see net.minecraft.world.entity.animal.allay.Allay
     */
    public static final class OfAllay {

        public static BooleanProperty generateCanDuplicateProperty() {
            return new BooleanProperty("CanDuplicate");
        }

        public static IntProperty generateDuplicationCooldownProperty() {
            return new IntProperty("DuplicationCooldown");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Monster
     */
    public static final class OfMonster {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Invul": INT
     *
     * @see net.minecraft.world.entity.boss.wither.WitherBoss
     */
    public static final class OfWitherBoss {

        public static IntProperty generateInvulProperty() {
            return new IntProperty("Invul");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.AbstractSkeleton
     */
    public static final class OfAbstractSkeleton {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "sheared": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Bogged
     */
    public static final class OfBogged {

        public static BooleanProperty generateShearedProperty() {
            return new BooleanProperty("sheared");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "StrayConversionTime": INT
     *
     * @see net.minecraft.world.entity.monster.Skeleton
     */
    public static final class OfSkeleton {

        public static IntProperty generateStrayConversionTimeProperty() {
            return new IntProperty("StrayConversionTime");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Stray
     */
    public static final class OfStray {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.WitherSkeleton
     */
    public static final class OfWitherSkeleton {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Blaze
     */
    public static final class OfBlaze {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "ExplosionRadius": BYTE
     *  - "Fuse": SHORT
     *  - "ignited": BOOLEAN
     *  - "powered": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Creeper
     */
    public static final class OfCreeper {

        public static ByteProperty generateExplosionRadiusProperty() {
            return new ByteProperty("ExplosionRadius");
        }

        public static ShortProperty generateFuseProperty() {
            return new ShortProperty("Fuse");
        }

        public static BooleanProperty generateIgnitedProperty() {
            return new BooleanProperty("ignited");
        }

        public static BooleanProperty generatePoweredProperty() {
            return new BooleanProperty("powered");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "carriedBlockState": [COMPOUND]
     * @see net.minecraft.world.entity.monster.EnderMan
     */
    public static final class OfEnderMan {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Lifetime": INT
     *
     * @see net.minecraft.world.entity.monster.Endermite
     */
    public static final class OfEndermite {

        public static IntProperty generateLifetimeProperty() {
            return new IntProperty("Lifetime");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Giant
     */
    public static final class OfGiant {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Guardian
     */
    public static final class OfGuardian {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.ElderGuardian
     */
    public static final class OfElderGuardian {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "PatrolLeader": BOOLEAN
     *  - "Patrolling": BOOLEAN
     *  - "patrol_target": BLOCK_POS
     *
     * @see net.minecraft.world.entity.monster.PatrollingMonster
     */
    public static final class OfPatrollingMonster {

        public static BooleanProperty generatePatrolLeaderProperty() {
            return new BooleanProperty("PatrolLeader");
        }

        public static BooleanProperty generatePatrollingProperty() {
            return new BooleanProperty("Patrolling");
        }

        public static BlockPosProperty generatePatrolTargetProperty() {
            return new BlockPosProperty("patrol_target");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CanJoinRaid": BOOLEAN
     *  - "RaidId": INT
     *  - "Wave": INT
     *
     * @see net.minecraft.world.entity.raid.Raider
     */
    public static final class OfRaider {

        public static BooleanProperty generateCanJoinRaidProperty() {
            return new BooleanProperty("CanJoinRaid");
        }

        public static IntProperty generateRaidIdProperty() {
            return new IntProperty("RaidId");
        }

        public static IntProperty generateWaveProperty() {
            return new IntProperty("Wave");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.AbstractIllager
     */
    public static final class OfAbstractIllager {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Pillager
     */
    public static final class OfPillager {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "SpellTicks": INT
     *
     * @see net.minecraft.world.entity.monster.SpellcasterIllager
     */
    public static final class OfSpellcasterIllager {

        public static IntProperty generateSpellTicksProperty() {
            return new IntProperty("SpellTicks");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Evoker
     */
    public static final class OfEvoker {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Illusioner
     */
    public static final class OfIllusioner {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Johnny": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Vindicator
     */
    public static final class OfVindicator {

        public static BooleanProperty generateJohnnyProperty() {
            return new BooleanProperty("Johnny");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "AttackTick": INT
     *  - "RoarTick": INT
     *  - "StunTick": INT
     *
     * @see net.minecraft.world.entity.monster.Ravager
     */
    public static final class OfRavager {

        public static IntProperty generateAttackTickProperty() {
            return new IntProperty("AttackTick");
        }

        public static IntProperty generateRoarTickProperty() {
            return new IntProperty("RoarTick");
        }

        public static IntProperty generateStunTickProperty() {
            return new IntProperty("StunTick");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Witch
     */
    public static final class OfWitch {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Silverfish
     */
    public static final class OfSilverfish {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Spider
     */
    public static final class OfSpider {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.CaveSpider
     */
    public static final class OfCaveSpider {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "BoundX": INT
     *  - "BoundY": INT
     *  - "BoundZ": INT
     *  - "LifeTicks": INT
     *
     * @see net.minecraft.world.entity.monster.Vex
     */
    public static final class OfVex {

        public static IntProperty generateBoundXProperty() {
            return new IntProperty("BoundX");
        }

        public static IntProperty generateBoundYProperty() {
            return new IntProperty("BoundY");
        }

        public static IntProperty generateBoundZProperty() {
            return new IntProperty("BoundZ");
        }

        public static IntProperty generateLifeTicksProperty() {
            return new IntProperty("LifeTicks");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "IsBaby": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Zoglin
     */
    public static final class OfZoglin {

        public static BooleanProperty generateIsBabyProperty() {
            return new BooleanProperty("IsBaby");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CanBreakDoors": BOOLEAN
     *  - "DrownedConversionTime": INT
     *  - "InWaterTime": INT
     *  - "IsBaby": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Zombie
     */
    public static final class OfZombie {

        public static BooleanProperty generateCanBreakDoorsProperty() {
            return new BooleanProperty("CanBreakDoors");
        }

        public static IntProperty generateDrownedConversionTimeProperty() {
            return new IntProperty("DrownedConversionTime");
        }

        public static IntProperty generateInWaterTimeProperty() {
            return new IntProperty("InWaterTime");
        }

        public static BooleanProperty generateIsBabyProperty() {
            return new BooleanProperty("IsBaby");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Drowned
     */
    public static final class OfDrowned {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Husk
     */
    public static final class OfHusk {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "ConversionPlayer": UUID
     *  - "ConversionTime": INT
     *  - "Xp": INT
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "Gossips": [[COMPOUND]] - "Offers": [ANY] - "VillagerData": [COMPOUND]
     * @see net.minecraft.world.entity.monster.ZombieVillager
     */
    public static final class OfZombieVillager {

        public static UuidProperty generateConversionPlayerProperty() {
            return new UuidProperty("ConversionPlayer");
        }

        public static IntProperty generateConversionTimeProperty() {
            return new IntProperty("ConversionTime");
        }

        public static IntProperty generateXpProperty() {
            return new IntProperty("Xp");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.ZombifiedPiglin
     */
    public static final class OfZombifiedPiglin {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.breeze.Breeze
     */
    public static final class OfBreeze {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "home_pos": BLOCK_POS
     *
     * @see net.minecraft.world.entity.monster.creaking.Creaking
     */
    public static final class OfCreaking {

        public static BlockPosProperty generateHomePosProperty() {
            return new BlockPosProperty("home_pos");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "IsImmuneToZombification": BOOLEAN
     *  - "TimeInOverworld": INT
     *
     * @see net.minecraft.world.entity.monster.piglin.AbstractPiglin
     */
    public static final class OfAbstractPiglin {

        public static BooleanProperty generateIsImmuneToZombificationProperty() {
            return new BooleanProperty("IsImmuneToZombification");
        }

        public static IntProperty generateTimeInOverworldProperty() {
            return new IntProperty("TimeInOverworld");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "CannotHunt": BOOLEAN
     *  - "IsBaby": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.piglin.Piglin
     */
    public static final class OfPiglin {

        public static BooleanProperty generateCannotHuntProperty() {
            return new BooleanProperty("CannotHunt");
        }

        public static BooleanProperty generateIsBabyProperty() {
            return new BooleanProperty("IsBaby");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.piglin.PiglinBrute
     */
    public static final class OfPiglinBrute {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "anger": [ANY] - "listener": [COMPOUND]
     * @see net.minecraft.world.entity.monster.warden.Warden
     */
    public static final class OfWarden {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.ambient.AmbientCreature
     */
    public static final class OfAmbientCreature {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "BatFlags": BYTE
     *
     * @see net.minecraft.world.entity.ambient.Bat
     */
    public static final class OfBat {

        public static ByteProperty generateBatFlagsProperty() {
            return new ByteProperty("BatFlags");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "DragonDeathTime": INT
     *  - "DragonPhase": INT
     *
     * @see net.minecraft.world.entity.boss.enderdragon.EnderDragon
     */
    public static final class OfEnderDragon {

        public static IntProperty generateDragonDeathTimeProperty() {
            return new IntProperty("DragonDeathTime");
        }

        public static IntProperty generateDragonPhaseProperty() {
            return new IntProperty("DragonPhase");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Size": INT
     *  - "wasOnGround": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Slime
     */
    public static final class OfSlime {

        public static IntProperty generateSizeProperty() {
            return new IntProperty("Size");
        }

        public static BooleanProperty generateWasOnGroundProperty() {
            return new BooleanProperty("wasOnGround");
        }
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.MagmaCube
     */
    public static final class OfMagmaCube {
    }

    /**
     * This class is automatically generated by the script. Please do not modify it.
     * Properties (NBT tags) of this entity:
     *  - "Body": [FLOAT]
     *  - "DisabledSlots": INT
     *  - "Head": [FLOAT]
     *  - "Invisible": BOOLEAN
     *  - "LeftArm": [FLOAT]
     *  - "LeftLeg": [FLOAT]
     *  - "Marker": BOOLEAN
     *  - "NoBasePlate": BOOLEAN
     *  - "RightArm": [FLOAT]
     *  - "RightLeg": [FLOAT]
     *  - "ShowArms": BOOLEAN
     *  - "Small": BOOLEAN
     * [Attention] Some properties have more than 1 type! Such situation is not supported yet:
     *  - "ArmorItems": [[COMPOUND]] - "HandItems": [[COMPOUND]] - "Pose": [COMPOUND]
     * @see net.minecraft.world.entity.decoration.ArmorStand
     */
    public static final class OfArmorStand {

        public static FloatListProperty generateBodyProperty() {
            return new FloatListProperty("Body");
        }

        public static IntProperty generateDisabledSlotsProperty() {
            return new IntProperty("DisabledSlots");
        }

        public static FloatListProperty generateHeadProperty() {
            return new FloatListProperty("Head");
        }

        public static BooleanProperty generateInvisibleProperty() {
            return new BooleanProperty("Invisible");
        }

        public static FloatListProperty generateLeftArmProperty() {
            return new FloatListProperty("LeftArm");
        }

        public static FloatListProperty generateLeftLegProperty() {
            return new FloatListProperty("LeftLeg");
        }

        public static BooleanProperty generateMarkerProperty() {
            return new BooleanProperty("Marker");
        }

        public static BooleanProperty generateNoBasePlateProperty() {
            return new BooleanProperty("NoBasePlate");
        }

        public static FloatListProperty generateRightArmProperty() {
            return new FloatListProperty("RightArm");
        }

        public static FloatListProperty generateRightLegProperty() {
            return new FloatListProperty("RightLeg");
        }

        public static BooleanProperty generateShowArmsProperty() {
            return new BooleanProperty("ShowArms");
        }

        public static BooleanProperty generateSmallProperty() {
            return new BooleanProperty("Small");
        }
    }
}
