package io.github.xienaoban.minecraft.biologydictionary.core.property;

import io.github.xienaoban.minecraft.biologydictionary.api.EntityProperty;
import io.github.xienaoban.minecraft.biologydictionary.core.property.preset.*;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;

import java.util.Map;
import java.util.Optional;

@Environment(EnvType.CLIENT)
public final class VanillaProperties {

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Air": SHORT
     *  - "CustomName": STRING
     *  - "CustomNameVisible": BOOLEAN
     *  - "FallDistance": FLOAT
     *  - "Fire": SHORT
     *  - "Glowing": BOOLEAN
     *  - "HasVisualFire": BOOLEAN
     *  - "Invulnerable": BOOLEAN
     *  - "Motion": [DOUBLE]
     *  - "NoGravity": BOOLEAN
     *  - "OnGround": BOOLEAN
     *  - "PortalCooldown": INT
     *  - "Pos": [DOUBLE]
     *  - "Rotation": [FLOAT]
     *  - "Silent": BOOLEAN
     *  - "Tags": [STRING]
     *  - "TicksFrozen": INT
     *  - "UUID": UUID
     * [Attention] Some properties cannot be recognized yet:
     *  - "Passengers": [ANY]
     *  - "id": [STRING]
     *
     * @see net.minecraft.world.entity.Entity
     */
    public static final class OfEntity {

        public static ShortProperty createAirProperty() {
            return new ShortProperty("Air");
        }

        public static ShortProperty getAirProperty(Map<String, EntityProperty> map) {
            return g(map, "Air");
        }

        public static StringProperty createCustomNameProperty() {
            return new StringProperty("CustomName");
        }

        public static StringProperty getCustomNameProperty(Map<String, EntityProperty> map) {
            return g(map, "CustomName");
        }

        public static BooleanProperty createCustomNameVisibleProperty() {
            return new BooleanProperty("CustomNameVisible");
        }

        public static BooleanProperty getCustomNameVisibleProperty(Map<String, EntityProperty> map) {
            return g(map, "CustomNameVisible");
        }

        public static FloatProperty createFallDistanceProperty() {
            return new FloatProperty("FallDistance");
        }

        public static FloatProperty getFallDistanceProperty(Map<String, EntityProperty> map) {
            return g(map, "FallDistance");
        }

        public static ShortProperty createFireProperty() {
            return new ShortProperty("Fire");
        }

        public static ShortProperty getFireProperty(Map<String, EntityProperty> map) {
            return g(map, "Fire");
        }

        public static BooleanProperty createGlowingProperty() {
            return new BooleanProperty("Glowing");
        }

        public static BooleanProperty getGlowingProperty(Map<String, EntityProperty> map) {
            return g(map, "Glowing");
        }

        public static BooleanProperty createHasVisualFireProperty() {
            return new BooleanProperty("HasVisualFire");
        }

        public static BooleanProperty getHasVisualFireProperty(Map<String, EntityProperty> map) {
            return g(map, "HasVisualFire");
        }

        public static BooleanProperty createInvulnerableProperty() {
            return new BooleanProperty("Invulnerable");
        }

        public static BooleanProperty getInvulnerableProperty(Map<String, EntityProperty> map) {
            return g(map, "Invulnerable");
        }

        public static DoubleListProperty createMotionProperty() {
            return new DoubleListProperty("Motion");
        }

        public static DoubleListProperty getMotionProperty(Map<String, EntityProperty> map) {
            return g(map, "Motion");
        }

        public static BooleanProperty createNoGravityProperty() {
            return new BooleanProperty("NoGravity");
        }

        public static BooleanProperty getNoGravityProperty(Map<String, EntityProperty> map) {
            return g(map, "NoGravity");
        }

        public static BooleanProperty createOnGroundProperty() {
            return new BooleanProperty("OnGround");
        }

        public static BooleanProperty getOnGroundProperty(Map<String, EntityProperty> map) {
            return g(map, "OnGround");
        }

        public static UnsupportedProperty createPassengersProperty() {
            return new UnsupportedProperty("Passengers");
        }

        public static UnsupportedProperty getPassengersProperty(Map<String, EntityProperty> map) {
            return g(map, "Passengers");
        }

        public static IntProperty createPortalCooldownProperty() {
            return new IntProperty("PortalCooldown");
        }

        public static IntProperty getPortalCooldownProperty(Map<String, EntityProperty> map) {
            return g(map, "PortalCooldown");
        }

        public static DoubleListProperty createPosProperty() {
            return new DoubleListProperty("Pos");
        }

        public static DoubleListProperty getPosProperty(Map<String, EntityProperty> map) {
            return g(map, "Pos");
        }

        public static FloatListProperty createRotationProperty() {
            return new FloatListProperty("Rotation");
        }

        public static FloatListProperty getRotationProperty(Map<String, EntityProperty> map) {
            return g(map, "Rotation");
        }

        public static BooleanProperty createSilentProperty() {
            return new BooleanProperty("Silent");
        }

        public static BooleanProperty getSilentProperty(Map<String, EntityProperty> map) {
            return g(map, "Silent");
        }

        public static StringListProperty createTagsProperty() {
            return new StringListProperty("Tags");
        }

        public static StringListProperty getTagsProperty(Map<String, EntityProperty> map) {
            return g(map, "Tags");
        }

        public static IntProperty createTicksFrozenProperty() {
            return new IntProperty("TicksFrozen");
        }

        public static IntProperty getTicksFrozenProperty(Map<String, EntityProperty> map) {
            return g(map, "TicksFrozen");
        }

        public static UuidProperty createUuidProperty() {
            return new UuidProperty("UUID");
        }

        public static UuidProperty getUuidProperty(Map<String, EntityProperty> map) {
            return g(map, "UUID");
        }

        public static UnsupportedProperty createIdProperty() {
            return new UnsupportedProperty("id");
        }

        public static UnsupportedProperty getIdProperty(Map<String, EntityProperty> map) {
            return g(map, "id");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "AbsorptionAmount": FLOAT
     *  - "DeathTime": SHORT
     *  - "FallFlying": BOOLEAN
     *  - "Health": FLOAT
     *  - "HurtByTimestamp": INT
     *  - "HurtTime": SHORT
     *  - "SleepingX": INT
     *  - "SleepingY": INT
     *  - "SleepingZ": INT
     * [Attention] Some properties cannot be recognized yet:
     *  - "Brain": [COMPOUND]
     *  - "Team": [STRING]
     *  - "active_effects": [[COMPOUND]]
     *  - "attributes": [[COMPOUND]]
     *
     * @see net.minecraft.world.entity.LivingEntity
     */
    public static final class OfLivingEntity {

        public static FloatProperty createAbsorptionAmountProperty() {
            return new FloatProperty("AbsorptionAmount");
        }

        public static FloatProperty getAbsorptionAmountProperty(Map<String, EntityProperty> map) {
            return g(map, "AbsorptionAmount");
        }

        public static UnsupportedProperty createBrainProperty() {
            return new UnsupportedProperty("Brain");
        }

        public static UnsupportedProperty getBrainProperty(Map<String, EntityProperty> map) {
            return g(map, "Brain");
        }

        public static ShortProperty createDeathTimeProperty() {
            return new ShortProperty("DeathTime");
        }

        public static ShortProperty getDeathTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "DeathTime");
        }

        public static BooleanProperty createFallFlyingProperty() {
            return new BooleanProperty("FallFlying");
        }

        public static BooleanProperty getFallFlyingProperty(Map<String, EntityProperty> map) {
            return g(map, "FallFlying");
        }

        public static FloatProperty createHealthProperty() {
            return new FloatProperty("Health");
        }

        public static FloatProperty getHealthProperty(Map<String, EntityProperty> map) {
            return g(map, "Health");
        }

        public static IntProperty createHurtByTimestampProperty() {
            return new IntProperty("HurtByTimestamp");
        }

        public static IntProperty getHurtByTimestampProperty(Map<String, EntityProperty> map) {
            return g(map, "HurtByTimestamp");
        }

        public static ShortProperty createHurtTimeProperty() {
            return new ShortProperty("HurtTime");
        }

        public static ShortProperty getHurtTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "HurtTime");
        }

        public static IntProperty createSleepingXProperty() {
            return new IntProperty("SleepingX");
        }

        public static IntProperty getSleepingXProperty(Map<String, EntityProperty> map) {
            return g(map, "SleepingX");
        }

        public static IntProperty createSleepingYProperty() {
            return new IntProperty("SleepingY");
        }

        public static IntProperty getSleepingYProperty(Map<String, EntityProperty> map) {
            return g(map, "SleepingY");
        }

        public static IntProperty createSleepingZProperty() {
            return new IntProperty("SleepingZ");
        }

        public static IntProperty getSleepingZProperty(Map<String, EntityProperty> map) {
            return g(map, "SleepingZ");
        }

        public static UnsupportedProperty createTeamProperty() {
            return new UnsupportedProperty("Team");
        }

        public static UnsupportedProperty getTeamProperty(Map<String, EntityProperty> map) {
            return g(map, "Team");
        }

        public static UnsupportedProperty createActiveEffectsProperty() {
            return new UnsupportedProperty("active_effects");
        }

        public static UnsupportedProperty getActiveEffectsProperty(Map<String, EntityProperty> map) {
            return g(map, "active_effects");
        }

        public static UnsupportedProperty createAttributesProperty() {
            return new UnsupportedProperty("attributes");
        }

        public static UnsupportedProperty getAttributesProperty(Map<String, EntityProperty> map) {
            return g(map, "attributes");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "ArmorDropChances": [FLOAT]
     *  - "ArmorItems": [ITEM_STACK]
     *  - "CanPickUpLoot": BOOLEAN
     *  - "DeathLootTable": STRING
     *  - "DeathLootTableSeed": LONG
     *  - "HandDropChances": [FLOAT]
     *  - "HandItems": [ITEM_STACK]
     *  - "LeftHanded": BOOLEAN
     *  - "NoAI": BOOLEAN
     *  - "PersistenceRequired": BOOLEAN
     *  - "body_armor_drop_chance": FLOAT
     *  - "body_armor_item": ITEM_STACK
     *
     * @see net.minecraft.world.entity.Mob
     */
    public static final class OfMob {

        public static FloatListProperty createArmorDropChancesProperty() {
            return new FloatListProperty("ArmorDropChances");
        }

        public static FloatListProperty getArmorDropChancesProperty(Map<String, EntityProperty> map) {
            return g(map, "ArmorDropChances");
        }

        public static ItemStackListProperty createArmorItemsProperty() {
            return new ItemStackListProperty("ArmorItems");
        }

        public static ItemStackListProperty getArmorItemsProperty(Map<String, EntityProperty> map) {
            return g(map, "ArmorItems");
        }

        public static BooleanProperty createCanPickUpLootProperty() {
            return new BooleanProperty("CanPickUpLoot");
        }

        public static BooleanProperty getCanPickUpLootProperty(Map<String, EntityProperty> map) {
            return g(map, "CanPickUpLoot");
        }

        public static StringProperty createDeathLootTableProperty() {
            return new StringProperty("DeathLootTable");
        }

        public static StringProperty getDeathLootTableProperty(Map<String, EntityProperty> map) {
            return g(map, "DeathLootTable");
        }

        public static LongProperty createDeathLootTableSeedProperty() {
            return new LongProperty("DeathLootTableSeed");
        }

        public static LongProperty getDeathLootTableSeedProperty(Map<String, EntityProperty> map) {
            return g(map, "DeathLootTableSeed");
        }

        public static FloatListProperty createHandDropChancesProperty() {
            return new FloatListProperty("HandDropChances");
        }

        public static FloatListProperty getHandDropChancesProperty(Map<String, EntityProperty> map) {
            return g(map, "HandDropChances");
        }

        public static ItemStackListProperty createHandItemsProperty() {
            return new ItemStackListProperty("HandItems");
        }

        public static ItemStackListProperty getHandItemsProperty(Map<String, EntityProperty> map) {
            return g(map, "HandItems");
        }

        public static BooleanProperty createLeftHandedProperty() {
            return new BooleanProperty("LeftHanded");
        }

        public static BooleanProperty getLeftHandedProperty(Map<String, EntityProperty> map) {
            return g(map, "LeftHanded");
        }

        public static BooleanProperty createNoAiProperty() {
            return new BooleanProperty("NoAI");
        }

        public static BooleanProperty getNoAiProperty(Map<String, EntityProperty> map) {
            return g(map, "NoAI");
        }

        public static BooleanProperty createPersistenceRequiredProperty() {
            return new BooleanProperty("PersistenceRequired");
        }

        public static BooleanProperty getPersistenceRequiredProperty(Map<String, EntityProperty> map) {
            return g(map, "PersistenceRequired");
        }

        public static FloatProperty createBodyArmorDropChanceProperty() {
            return new FloatProperty("body_armor_drop_chance");
        }

        public static FloatProperty getBodyArmorDropChanceProperty(Map<String, EntityProperty> map) {
            return g(map, "body_armor_drop_chance");
        }

        public static ItemStackProperty createBodyArmorItemProperty() {
            return new ItemStackProperty("body_armor_item");
        }

        public static ItemStackProperty getBodyArmorItemProperty(Map<String, EntityProperty> map) {
            return g(map, "body_armor_item");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.FlyingMob
     */
    public static final class OfFlyingMob {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "ExplosionPower": BYTE
     *
     * @see net.minecraft.world.entity.monster.Ghast
     */
    public static final class OfGhast {

        public static ByteProperty createExplosionPowerProperty() {
            return new ByteProperty("ExplosionPower");
        }

        public static ByteProperty getExplosionPowerProperty(Map<String, EntityProperty> map) {
            return g(map, "ExplosionPower");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "AX": INT
     *  - "AY": INT
     *  - "AZ": INT
     *  - "Size": INT
     *
     * @see net.minecraft.world.entity.monster.Phantom
     */
    public static final class OfPhantom {

        public static IntProperty createAxProperty() {
            return new IntProperty("AX");
        }

        public static IntProperty getAxProperty(Map<String, EntityProperty> map) {
            return g(map, "AX");
        }

        public static IntProperty createAyProperty() {
            return new IntProperty("AY");
        }

        public static IntProperty getAyProperty(Map<String, EntityProperty> map) {
            return g(map, "AY");
        }

        public static IntProperty createAzProperty() {
            return new IntProperty("AZ");
        }

        public static IntProperty getAzProperty(Map<String, EntityProperty> map) {
            return g(map, "AZ");
        }

        public static IntProperty createSizeProperty() {
            return new IntProperty("Size");
        }

        public static IntProperty getSizeProperty(Map<String, EntityProperty> map) {
            return g(map, "Size");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.PathfinderMob
     */
    public static final class OfPathfinderMob {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Age": INT
     *  - "ForcedAge": INT
     *
     * @see net.minecraft.world.entity.AgeableMob
     */
    public static final class OfAgeableMob {

        public static IntProperty createAgeProperty() {
            return new IntProperty("Age");
        }

        public static IntProperty getAgeProperty(Map<String, EntityProperty> map) {
            return g(map, "Age");
        }

        public static IntProperty createForcedAgeProperty() {
            return new IntProperty("ForcedAge");
        }

        public static IntProperty getForcedAgeProperty(Map<String, EntityProperty> map) {
            return g(map, "ForcedAge");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.AgeableWaterCreature
     */
    public static final class OfAgeableWaterCreature {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "GotFish": BOOLEAN
     *  - "Moistness": INT
     *  - "TreasurePosX": INT
     *  - "TreasurePosY": INT
     *  - "TreasurePosZ": INT
     *
     * @see net.minecraft.world.entity.animal.Dolphin
     */
    public static final class OfDolphin {

        public static BooleanProperty createGotFishProperty() {
            return new BooleanProperty("GotFish");
        }

        public static BooleanProperty getGotFishProperty(Map<String, EntityProperty> map) {
            return g(map, "GotFish");
        }

        public static IntProperty createMoistnessProperty() {
            return new IntProperty("Moistness");
        }

        public static IntProperty getMoistnessProperty(Map<String, EntityProperty> map) {
            return g(map, "Moistness");
        }

        public static IntProperty createTreasurePosXProperty() {
            return new IntProperty("TreasurePosX");
        }

        public static IntProperty getTreasurePosXProperty(Map<String, EntityProperty> map) {
            return g(map, "TreasurePosX");
        }

        public static IntProperty createTreasurePosYProperty() {
            return new IntProperty("TreasurePosY");
        }

        public static IntProperty getTreasurePosYProperty(Map<String, EntityProperty> map) {
            return g(map, "TreasurePosY");
        }

        public static IntProperty createTreasurePosZProperty() {
            return new IntProperty("TreasurePosZ");
        }

        public static IntProperty getTreasurePosZProperty(Map<String, EntityProperty> map) {
            return g(map, "TreasurePosZ");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Squid
     */
    public static final class OfSquid {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "DarkTicksRemaining": INT
     *
     * @see net.minecraft.world.entity.GlowSquid
     */
    public static final class OfGlowSquid {

        public static IntProperty createDarkTicksRemainingProperty() {
            return new IntProperty("DarkTicksRemaining");
        }

        public static IntProperty getDarkTicksRemainingProperty(Map<String, EntityProperty> map) {
            return g(map, "DarkTicksRemaining");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "InLove": INT
     *  - "LoveCause": UUID
     *
     * @see net.minecraft.world.entity.animal.Animal
     */
    public static final class OfAnimal {

        public static IntProperty createInLoveProperty() {
            return new IntProperty("InLove");
        }

        public static IntProperty getInLoveProperty(Map<String, EntityProperty> map) {
            return g(map, "InLove");
        }

        public static UuidProperty createLoveCauseProperty() {
            return new UuidProperty("LoveCause");
        }

        public static UuidProperty getLoveCauseProperty(Map<String, EntityProperty> map) {
            return g(map, "LoveCause");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Sitting": BOOLEAN
     * [Attention] Some properties cannot be recognized yet:
     *  - "Owner": [STRING, UUID]
     *
     * @see net.minecraft.world.entity.TamableAnimal
     */
    public static final class OfTamableAnimal {

        public static UnsupportedProperty createOwnerProperty() {
            return new UnsupportedProperty("Owner");
        }

        public static UnsupportedProperty getOwnerProperty(Map<String, EntityProperty> map) {
            return g(map, "Owner");
        }

        public static BooleanProperty createSittingProperty() {
            return new BooleanProperty("Sitting");
        }

        public static BooleanProperty getSittingProperty(Map<String, EntityProperty> map) {
            return g(map, "Sitting");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CollarColor": BYTE
     *  - "variant": STRING
     *
     * @see net.minecraft.world.entity.animal.Cat
     */
    public static final class OfCat {

        public static ByteProperty createCollarColorProperty() {
            return new ByteProperty("CollarColor");
        }

        public static ByteProperty getCollarColorProperty(Map<String, EntityProperty> map) {
            return g(map, "CollarColor");
        }

        public static StringProperty createVariantProperty() {
            return new StringProperty("variant");
        }

        public static StringProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties cannot be recognized yet:
     *  - "id": [STRING]
     *
     * @see net.minecraft.world.entity.animal.ShoulderRidingEntity
     */
    public static final class OfShoulderRidingEntity {

        public static UnsupportedProperty createIdProperty() {
            return new UnsupportedProperty("id");
        }

        public static UnsupportedProperty getIdProperty(Map<String, EntityProperty> map) {
            return g(map, "id");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.Parrot
     */
    public static final class OfParrot {

        public static IntProperty createVariantProperty() {
            return new IntProperty("Variant");
        }

        public static IntProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "Variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CollarColor": BYTE
     *  - "variant": STRING
     *
     * @see net.minecraft.world.entity.animal.Wolf
     */
    public static final class OfWolf {

        public static ByteProperty createCollarColorProperty() {
            return new ByteProperty("CollarColor");
        }

        public static ByteProperty getCollarColorProperty(Map<String, EntityProperty> map) {
            return g(map, "CollarColor");
        }

        public static StringProperty createVariantProperty() {
            return new StringProperty("variant");
        }

        public static StringProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CannotEnterHiveTicks": INT
     *  - "CropsGrownSincePollination": INT
     *  - "HasNectar": BOOLEAN
     *  - "HasStung": BOOLEAN
     *  - "TicksSincePollination": INT
     *  - "flower_pos": BLOCK_POS
     *  - "hive_pos": BLOCK_POS
     *
     * @see net.minecraft.world.entity.animal.Bee
     */
    public static final class OfBee {

        public static IntProperty createCannotEnterHiveTicksProperty() {
            return new IntProperty("CannotEnterHiveTicks");
        }

        public static IntProperty getCannotEnterHiveTicksProperty(Map<String, EntityProperty> map) {
            return g(map, "CannotEnterHiveTicks");
        }

        public static IntProperty createCropsGrownSincePollinationProperty() {
            return new IntProperty("CropsGrownSincePollination");
        }

        public static IntProperty getCropsGrownSincePollinationProperty(Map<String, EntityProperty> map) {
            return g(map, "CropsGrownSincePollination");
        }

        public static BooleanProperty createHasNectarProperty() {
            return new BooleanProperty("HasNectar");
        }

        public static BooleanProperty getHasNectarProperty(Map<String, EntityProperty> map) {
            return g(map, "HasNectar");
        }

        public static BooleanProperty createHasStungProperty() {
            return new BooleanProperty("HasStung");
        }

        public static BooleanProperty getHasStungProperty(Map<String, EntityProperty> map) {
            return g(map, "HasStung");
        }

        public static IntProperty createTicksSincePollinationProperty() {
            return new IntProperty("TicksSincePollination");
        }

        public static IntProperty getTicksSincePollinationProperty(Map<String, EntityProperty> map) {
            return g(map, "TicksSincePollination");
        }

        public static BlockPosProperty createFlowerPosProperty() {
            return new BlockPosProperty("flower_pos");
        }

        public static BlockPosProperty getFlowerPosProperty(Map<String, EntityProperty> map) {
            return g(map, "flower_pos");
        }

        public static BlockPosProperty createHivePosProperty() {
            return new BlockPosProperty("hive_pos");
        }

        public static BlockPosProperty getHivePosProperty(Map<String, EntityProperty> map) {
            return g(map, "hive_pos");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "EggLayTime": INT
     *  - "IsChickenJockey": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.Chicken
     */
    public static final class OfChicken {

        public static IntProperty createEggLayTimeProperty() {
            return new IntProperty("EggLayTime");
        }

        public static IntProperty getEggLayTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "EggLayTime");
        }

        public static BooleanProperty createIsChickenJockeyProperty() {
            return new BooleanProperty("IsChickenJockey");
        }

        public static BooleanProperty getIsChickenJockeyProperty(Map<String, EntityProperty> map) {
            return g(map, "IsChickenJockey");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Cow
     */
    public static final class OfCow {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Type": STRING
     * [Attention] Some properties cannot be recognized yet:
     *  - "stew_effects": [[ANY]]
     *
     * @see net.minecraft.world.entity.animal.MushroomCow
     */
    public static final class OfMushroomCow {

        public static StringProperty createTypeProperty() {
            return new StringProperty("Type");
        }

        public static StringProperty getTypeProperty(Map<String, EntityProperty> map) {
            return g(map, "Type");
        }

        public static UnsupportedProperty createStewEffectsProperty() {
            return new UnsupportedProperty("stew_effects");
        }

        public static UnsupportedProperty getStewEffectsProperty(Map<String, EntityProperty> map) {
            return g(map, "stew_effects");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Crouching": BOOLEAN
     *  - "Sitting": BOOLEAN
     *  - "Sleeping": BOOLEAN
     *  - "Trusted": [INT_ARRAY]
     *  - "Type": STRING
     *
     * @see net.minecraft.world.entity.animal.Fox
     */
    public static final class OfFox {

        public static BooleanProperty createCrouchingProperty() {
            return new BooleanProperty("Crouching");
        }

        public static BooleanProperty getCrouchingProperty(Map<String, EntityProperty> map) {
            return g(map, "Crouching");
        }

        public static BooleanProperty createSittingProperty() {
            return new BooleanProperty("Sitting");
        }

        public static BooleanProperty getSittingProperty(Map<String, EntityProperty> map) {
            return g(map, "Sitting");
        }

        public static BooleanProperty createSleepingProperty() {
            return new BooleanProperty("Sleeping");
        }

        public static BooleanProperty getSleepingProperty(Map<String, EntityProperty> map) {
            return g(map, "Sleeping");
        }

        public static UuidListProperty createTrustedProperty() {
            return new UuidListProperty("Trusted");
        }

        public static UuidListProperty getTrustedProperty(Map<String, EntityProperty> map) {
            return g(map, "Trusted");
        }

        public static StringProperty createTypeProperty() {
            return new StringProperty("Type");
        }

        public static StringProperty getTypeProperty(Map<String, EntityProperty> map) {
            return g(map, "Type");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Trusting": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.Ocelot
     */
    public static final class OfOcelot {

        public static BooleanProperty createTrustingProperty() {
            return new BooleanProperty("Trusting");
        }

        public static BooleanProperty getTrustingProperty(Map<String, EntityProperty> map) {
            return g(map, "Trusting");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "HiddenGene": STRING
     *  - "MainGene": STRING
     *
     * @see net.minecraft.world.entity.animal.Panda
     */
    public static final class OfPanda {

        public static StringProperty createHiddenGeneProperty() {
            return new StringProperty("HiddenGene");
        }

        public static StringProperty getHiddenGeneProperty(Map<String, EntityProperty> map) {
            return g(map, "HiddenGene");
        }

        public static StringProperty createMainGeneProperty() {
            return new StringProperty("MainGene");
        }

        public static StringProperty getMainGeneProperty(Map<String, EntityProperty> map) {
            return g(map, "MainGene");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Pig
     */
    public static final class OfPig {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.PolarBear
     */
    public static final class OfPolarBear {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "MoreCarrotTicks": INT
     *  - "RabbitType": INT
     *
     * @see net.minecraft.world.entity.animal.Rabbit
     */
    public static final class OfRabbit {

        public static IntProperty createMoreCarrotTicksProperty() {
            return new IntProperty("MoreCarrotTicks");
        }

        public static IntProperty getMoreCarrotTicksProperty(Map<String, EntityProperty> map) {
            return g(map, "MoreCarrotTicks");
        }

        public static IntProperty createRabbitTypeProperty() {
            return new IntProperty("RabbitType");
        }

        public static IntProperty getRabbitTypeProperty(Map<String, EntityProperty> map) {
            return g(map, "RabbitType");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Color": BYTE
     *  - "Sheared": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.Sheep
     */
    public static final class OfSheep {

        public static ByteProperty createColorProperty() {
            return new ByteProperty("Color");
        }

        public static ByteProperty getColorProperty(Map<String, EntityProperty> map) {
            return g(map, "Color");
        }

        public static BooleanProperty createShearedProperty() {
            return new BooleanProperty("Sheared");
        }

        public static BooleanProperty getShearedProperty(Map<String, EntityProperty> map) {
            return g(map, "Sheared");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "HasEgg": BOOLEAN
     *  - "HomePosX": INT
     *  - "HomePosY": INT
     *  - "HomePosZ": INT
     *  - "TravelPosX": INT
     *  - "TravelPosY": INT
     *  - "TravelPosZ": INT
     *
     * @see net.minecraft.world.entity.animal.Turtle
     */
    public static final class OfTurtle {

        public static BooleanProperty createHasEggProperty() {
            return new BooleanProperty("HasEgg");
        }

        public static BooleanProperty getHasEggProperty(Map<String, EntityProperty> map) {
            return g(map, "HasEgg");
        }

        public static IntProperty createHomePosXProperty() {
            return new IntProperty("HomePosX");
        }

        public static IntProperty getHomePosXProperty(Map<String, EntityProperty> map) {
            return g(map, "HomePosX");
        }

        public static IntProperty createHomePosYProperty() {
            return new IntProperty("HomePosY");
        }

        public static IntProperty getHomePosYProperty(Map<String, EntityProperty> map) {
            return g(map, "HomePosY");
        }

        public static IntProperty createHomePosZProperty() {
            return new IntProperty("HomePosZ");
        }

        public static IntProperty getHomePosZProperty(Map<String, EntityProperty> map) {
            return g(map, "HomePosZ");
        }

        public static IntProperty createTravelPosXProperty() {
            return new IntProperty("TravelPosX");
        }

        public static IntProperty getTravelPosXProperty(Map<String, EntityProperty> map) {
            return g(map, "TravelPosX");
        }

        public static IntProperty createTravelPosYProperty() {
            return new IntProperty("TravelPosY");
        }

        public static IntProperty getTravelPosYProperty(Map<String, EntityProperty> map) {
            return g(map, "TravelPosY");
        }

        public static IntProperty createTravelPosZProperty() {
            return new IntProperty("TravelPosZ");
        }

        public static IntProperty getTravelPosZProperty(Map<String, EntityProperty> map) {
            return g(map, "TravelPosZ");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "scute_time": INT
     *  - "state": STRING
     *
     * @see net.minecraft.world.entity.animal.armadillo.Armadillo
     */
    public static final class OfArmadillo {

        public static IntProperty createScuteTimeProperty() {
            return new IntProperty("scute_time");
        }

        public static IntProperty getScuteTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "scute_time");
        }

        public static StringProperty createStateProperty() {
            return new StringProperty("state");
        }

        public static StringProperty getStateProperty(Map<String, EntityProperty> map) {
            return g(map, "state");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Age": INT
     *  - "FromBucket": BOOLEAN
     *  - "HuntingCooldown": LONG
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.axolotl.Axolotl
     */
    public static final class OfAxolotl {

        public static IntProperty createAgeProperty() {
            return new IntProperty("Age");
        }

        public static IntProperty getAgeProperty(Map<String, EntityProperty> map) {
            return g(map, "Age");
        }

        public static BooleanProperty createFromBucketProperty() {
            return new BooleanProperty("FromBucket");
        }

        public static BooleanProperty getFromBucketProperty(Map<String, EntityProperty> map) {
            return g(map, "FromBucket");
        }

        public static LongProperty createHuntingCooldownProperty() {
            return new LongProperty("HuntingCooldown");
        }

        public static LongProperty getHuntingCooldownProperty(Map<String, EntityProperty> map) {
            return g(map, "HuntingCooldown");
        }

        public static IntProperty createVariantProperty() {
            return new IntProperty("Variant");
        }

        public static IntProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "Variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "variant": STRING
     *
     * @see net.minecraft.world.entity.animal.frog.Frog
     */
    public static final class OfFrog {

        public static StringProperty createVariantProperty() {
            return new StringProperty("variant");
        }

        public static StringProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "HasLeftHorn": BOOLEAN
     *  - "HasRightHorn": BOOLEAN
     *  - "IsScreamingGoat": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.goat.Goat
     */
    public static final class OfGoat {

        public static BooleanProperty createHasLeftHornProperty() {
            return new BooleanProperty("HasLeftHorn");
        }

        public static BooleanProperty getHasLeftHornProperty(Map<String, EntityProperty> map) {
            return g(map, "HasLeftHorn");
        }

        public static BooleanProperty createHasRightHornProperty() {
            return new BooleanProperty("HasRightHorn");
        }

        public static BooleanProperty getHasRightHornProperty(Map<String, EntityProperty> map) {
            return g(map, "HasRightHorn");
        }

        public static BooleanProperty createIsScreamingGoatProperty() {
            return new BooleanProperty("IsScreamingGoat");
        }

        public static BooleanProperty getIsScreamingGoatProperty(Map<String, EntityProperty> map) {
            return g(map, "IsScreamingGoat");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Bred": BOOLEAN
     *  - "EatingHaystack": BOOLEAN
     *  - "SaddleItem": ITEM_STACK
     *  - "Tame": BOOLEAN
     *  - "Temper": INT
     * [Attention] Some properties cannot be recognized yet:
     *  - "Owner": [STRING, UUID]
     *
     * @see net.minecraft.world.entity.animal.horse.AbstractHorse
     */
    public static final class OfAbstractHorse {

        public static BooleanProperty createBredProperty() {
            return new BooleanProperty("Bred");
        }

        public static BooleanProperty getBredProperty(Map<String, EntityProperty> map) {
            return g(map, "Bred");
        }

        public static BooleanProperty createEatingHaystackProperty() {
            return new BooleanProperty("EatingHaystack");
        }

        public static BooleanProperty getEatingHaystackProperty(Map<String, EntityProperty> map) {
            return g(map, "EatingHaystack");
        }

        public static UnsupportedProperty createOwnerProperty() {
            return new UnsupportedProperty("Owner");
        }

        public static UnsupportedProperty getOwnerProperty(Map<String, EntityProperty> map) {
            return g(map, "Owner");
        }

        public static ItemStackProperty createSaddleItemProperty() {
            return new ItemStackProperty("SaddleItem");
        }

        public static ItemStackProperty getSaddleItemProperty(Map<String, EntityProperty> map) {
            return g(map, "SaddleItem");
        }

        public static BooleanProperty createTameProperty() {
            return new BooleanProperty("Tame");
        }

        public static BooleanProperty getTameProperty(Map<String, EntityProperty> map) {
            return g(map, "Tame");
        }

        public static IntProperty createTemperProperty() {
            return new IntProperty("Temper");
        }

        public static IntProperty getTemperProperty(Map<String, EntityProperty> map) {
            return g(map, "Temper");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "LastPoseTick": LONG
     *
     * @see net.minecraft.world.entity.animal.camel.Camel
     */
    public static final class OfCamel {

        public static LongProperty createLastPoseTickProperty() {
            return new LongProperty("LastPoseTick");
        }

        public static LongProperty getLastPoseTickProperty(Map<String, EntityProperty> map) {
            return g(map, "LastPoseTick");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "ChestedHorse": BOOLEAN
     *  - "Items": [ITEM_STACK]
     *
     * @see net.minecraft.world.entity.animal.horse.AbstractChestedHorse
     */
    public static final class OfAbstractChestedHorse {

        public static BooleanProperty createChestedHorseProperty() {
            return new BooleanProperty("ChestedHorse");
        }

        public static BooleanProperty getChestedHorseProperty(Map<String, EntityProperty> map) {
            return g(map, "ChestedHorse");
        }

        public static ItemStackListProperty createItemsProperty() {
            return new ItemStackListProperty("Items");
        }

        public static ItemStackListProperty getItemsProperty(Map<String, EntityProperty> map) {
            return g(map, "Items");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.horse.Donkey
     */
    public static final class OfDonkey {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Strength": INT
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.horse.Llama
     */
    public static final class OfLlama {

        public static IntProperty createStrengthProperty() {
            return new IntProperty("Strength");
        }

        public static IntProperty getStrengthProperty(Map<String, EntityProperty> map) {
            return g(map, "Strength");
        }

        public static IntProperty createVariantProperty() {
            return new IntProperty("Variant");
        }

        public static IntProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "Variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "DespawnDelay": INT
     *
     * @see net.minecraft.world.entity.animal.horse.TraderLlama
     */
    public static final class OfTraderLlama {

        public static IntProperty createDespawnDelayProperty() {
            return new IntProperty("DespawnDelay");
        }

        public static IntProperty getDespawnDelayProperty(Map<String, EntityProperty> map) {
            return g(map, "DespawnDelay");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.horse.Mule
     */
    public static final class OfMule {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.horse.Horse
     */
    public static final class OfHorse {

        public static IntProperty createVariantProperty() {
            return new IntProperty("Variant");
        }

        public static IntProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "Variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "SkeletonTrap": BOOLEAN
     *  - "SkeletonTrapTime": INT
     *
     * @see net.minecraft.world.entity.animal.horse.SkeletonHorse
     */
    public static final class OfSkeletonHorse {

        public static BooleanProperty createSkeletonTrapProperty() {
            return new BooleanProperty("SkeletonTrap");
        }

        public static BooleanProperty getSkeletonTrapProperty(Map<String, EntityProperty> map) {
            return g(map, "SkeletonTrap");
        }

        public static IntProperty createSkeletonTrapTimeProperty() {
            return new IntProperty("SkeletonTrapTime");
        }

        public static IntProperty getSkeletonTrapTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "SkeletonTrapTime");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.horse.ZombieHorse
     */
    public static final class OfZombieHorse {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.sniffer.Sniffer
     */
    public static final class OfSniffer {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Strider
     */
    public static final class OfStrider {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CannotBeHunted": BOOLEAN
     *  - "IsImmuneToZombification": BOOLEAN
     *  - "TimeInOverworld": INT
     *
     * @see net.minecraft.world.entity.monster.hoglin.Hoglin
     */
    public static final class OfHoglin {

        public static BooleanProperty createCannotBeHuntedProperty() {
            return new BooleanProperty("CannotBeHunted");
        }

        public static BooleanProperty getCannotBeHuntedProperty(Map<String, EntityProperty> map) {
            return g(map, "CannotBeHunted");
        }

        public static BooleanProperty createIsImmuneToZombificationProperty() {
            return new BooleanProperty("IsImmuneToZombification");
        }

        public static BooleanProperty getIsImmuneToZombificationProperty(Map<String, EntityProperty> map) {
            return g(map, "IsImmuneToZombification");
        }

        public static IntProperty createTimeInOverworldProperty() {
            return new IntProperty("TimeInOverworld");
        }

        public static IntProperty getTimeInOverworldProperty(Map<String, EntityProperty> map) {
            return g(map, "TimeInOverworld");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties cannot be recognized yet:
     *  - "Offers": [ANY]
     *
     * @see net.minecraft.world.entity.npc.AbstractVillager
     */
    public static final class OfAbstractVillager {

        public static UnsupportedProperty createOffersProperty() {
            return new UnsupportedProperty("Offers");
        }

        public static UnsupportedProperty getOffersProperty(Map<String, EntityProperty> map) {
            return g(map, "Offers");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "AssignProfessionWhenSpawned": BOOLEAN
     *  - "FoodLevel": BYTE
     *  - "LastGossipDecay": LONG
     *  - "LastRestock": LONG
     *  - "RestocksToday": INT
     *  - "Xp": INT
     * [Attention] Some properties cannot be recognized yet:
     *  - "Gossips": [[COMPOUND]]
     *  - "VillagerData": [COMPOUND]
     *
     * @see net.minecraft.world.entity.npc.Villager
     */
    public static final class OfVillager {

        public static BooleanProperty createAssignProfessionWhenSpawnedProperty() {
            return new BooleanProperty("AssignProfessionWhenSpawned");
        }

        public static BooleanProperty getAssignProfessionWhenSpawnedProperty(Map<String, EntityProperty> map) {
            return g(map, "AssignProfessionWhenSpawned");
        }

        public static ByteProperty createFoodLevelProperty() {
            return new ByteProperty("FoodLevel");
        }

        public static ByteProperty getFoodLevelProperty(Map<String, EntityProperty> map) {
            return g(map, "FoodLevel");
        }

        public static UnsupportedProperty createGossipsProperty() {
            return new UnsupportedProperty("Gossips");
        }

        public static UnsupportedProperty getGossipsProperty(Map<String, EntityProperty> map) {
            return g(map, "Gossips");
        }

        public static LongProperty createLastGossipDecayProperty() {
            return new LongProperty("LastGossipDecay");
        }

        public static LongProperty getLastGossipDecayProperty(Map<String, EntityProperty> map) {
            return g(map, "LastGossipDecay");
        }

        public static LongProperty createLastRestockProperty() {
            return new LongProperty("LastRestock");
        }

        public static LongProperty getLastRestockProperty(Map<String, EntityProperty> map) {
            return g(map, "LastRestock");
        }

        public static IntProperty createRestocksTodayProperty() {
            return new IntProperty("RestocksToday");
        }

        public static IntProperty getRestocksTodayProperty(Map<String, EntityProperty> map) {
            return g(map, "RestocksToday");
        }

        public static UnsupportedProperty createVillagerDataProperty() {
            return new UnsupportedProperty("VillagerData");
        }

        public static UnsupportedProperty getVillagerDataProperty(Map<String, EntityProperty> map) {
            return g(map, "VillagerData");
        }

        public static IntProperty createXpProperty() {
            return new IntProperty("Xp");
        }

        public static IntProperty getXpProperty(Map<String, EntityProperty> map) {
            return g(map, "Xp");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "DespawnDelay": INT
     *  - "wander_target": BLOCK_POS
     *
     * @see net.minecraft.world.entity.npc.WanderingTrader
     */
    public static final class OfWanderingTrader {

        public static IntProperty createDespawnDelayProperty() {
            return new IntProperty("DespawnDelay");
        }

        public static IntProperty getDespawnDelayProperty(Map<String, EntityProperty> map) {
            return g(map, "DespawnDelay");
        }

        public static BlockPosProperty createWanderTargetProperty() {
            return new BlockPosProperty("wander_target");
        }

        public static BlockPosProperty getWanderTargetProperty(Map<String, EntityProperty> map) {
            return g(map, "wander_target");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.AbstractGolem
     */
    public static final class OfAbstractGolem {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "PlayerCreated": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.IronGolem
     */
    public static final class OfIronGolem {

        public static BooleanProperty createPlayerCreatedProperty() {
            return new BooleanProperty("PlayerCreated");
        }

        public static BooleanProperty getPlayerCreatedProperty(Map<String, EntityProperty> map) {
            return g(map, "PlayerCreated");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Pumpkin": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.SnowGolem
     */
    public static final class OfSnowGolem {

        public static BooleanProperty createPumpkinProperty() {
            return new BooleanProperty("Pumpkin");
        }

        public static BooleanProperty getPumpkinProperty(Map<String, EntityProperty> map) {
            return g(map, "Pumpkin");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "AttachFace": BYTE
     *  - "Color": BYTE
     *  - "Peek": BYTE
     *
     * @see net.minecraft.world.entity.monster.Shulker
     */
    public static final class OfShulker {

        public static ByteProperty createAttachFaceProperty() {
            return new ByteProperty("AttachFace");
        }

        public static ByteProperty getAttachFaceProperty(Map<String, EntityProperty> map) {
            return g(map, "AttachFace");
        }

        public static ByteProperty createColorProperty() {
            return new ByteProperty("Color");
        }

        public static ByteProperty getColorProperty(Map<String, EntityProperty> map) {
            return g(map, "Color");
        }

        public static ByteProperty createPeekProperty() {
            return new ByteProperty("Peek");
        }

        public static ByteProperty getPeekProperty(Map<String, EntityProperty> map) {
            return g(map, "Peek");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.WaterAnimal
     */
    public static final class OfWaterAnimal {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "FromBucket": BOOLEAN
     *
     * @see net.minecraft.world.entity.animal.AbstractFish
     */
    public static final class OfAbstractFish {

        public static BooleanProperty createFromBucketProperty() {
            return new BooleanProperty("FromBucket");
        }

        public static BooleanProperty getFromBucketProperty(Map<String, EntityProperty> map) {
            return g(map, "FromBucket");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.AbstractSchoolingFish
     */
    public static final class OfAbstractSchoolingFish {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.animal.Cod
     */
    public static final class OfCod {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "type": STRING
     *
     * @see net.minecraft.world.entity.animal.Salmon
     */
    public static final class OfSalmon {

        public static StringProperty createTypeProperty() {
            return new StringProperty("type");
        }

        public static StringProperty getTypeProperty(Map<String, EntityProperty> map) {
            return g(map, "type");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "BucketVariantTag": INT
     *  - "Variant": INT
     *
     * @see net.minecraft.world.entity.animal.TropicalFish
     */
    public static final class OfTropicalFish {

        public static IntProperty createBucketVariantTagProperty() {
            return new IntProperty("BucketVariantTag");
        }

        public static IntProperty getBucketVariantTagProperty(Map<String, EntityProperty> map) {
            return g(map, "BucketVariantTag");
        }

        public static IntProperty createVariantProperty() {
            return new IntProperty("Variant");
        }

        public static IntProperty getVariantProperty(Map<String, EntityProperty> map) {
            return g(map, "Variant");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "PuffState": INT
     *
     * @see net.minecraft.world.entity.animal.Pufferfish
     */
    public static final class OfPufferfish {

        public static IntProperty createPuffStateProperty() {
            return new IntProperty("PuffState");
        }

        public static IntProperty getPuffStateProperty(Map<String, EntityProperty> map) {
            return g(map, "PuffState");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Age": INT
     *
     * @see net.minecraft.world.entity.animal.frog.Tadpole
     */
    public static final class OfTadpole {

        public static IntProperty createAgeProperty() {
            return new IntProperty("Age");
        }

        public static IntProperty getAgeProperty(Map<String, EntityProperty> map) {
            return g(map, "Age");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CanDuplicate": BOOLEAN
     *  - "DuplicationCooldown": INT
     * [Attention] Some properties cannot be recognized yet:
     *  - "listener": [COMPOUND]
     *
     * @see net.minecraft.world.entity.animal.allay.Allay
     */
    public static final class OfAllay {

        public static BooleanProperty createCanDuplicateProperty() {
            return new BooleanProperty("CanDuplicate");
        }

        public static BooleanProperty getCanDuplicateProperty(Map<String, EntityProperty> map) {
            return g(map, "CanDuplicate");
        }

        public static IntProperty createDuplicationCooldownProperty() {
            return new IntProperty("DuplicationCooldown");
        }

        public static IntProperty getDuplicationCooldownProperty(Map<String, EntityProperty> map) {
            return g(map, "DuplicationCooldown");
        }

        public static UnsupportedProperty createListenerProperty() {
            return new UnsupportedProperty("listener");
        }

        public static UnsupportedProperty getListenerProperty(Map<String, EntityProperty> map) {
            return g(map, "listener");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Monster
     */
    public static final class OfMonster {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Invul": INT
     *
     * @see net.minecraft.world.entity.boss.wither.WitherBoss
     */
    public static final class OfWitherBoss {

        public static IntProperty createInvulProperty() {
            return new IntProperty("Invul");
        }

        public static IntProperty getInvulProperty(Map<String, EntityProperty> map) {
            return g(map, "Invul");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.AbstractSkeleton
     */
    public static final class OfAbstractSkeleton {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "sheared": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Bogged
     */
    public static final class OfBogged {

        public static BooleanProperty createShearedProperty() {
            return new BooleanProperty("sheared");
        }

        public static BooleanProperty getShearedProperty(Map<String, EntityProperty> map) {
            return g(map, "sheared");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "StrayConversionTime": INT
     *
     * @see net.minecraft.world.entity.monster.Skeleton
     */
    public static final class OfSkeleton {

        public static IntProperty createStrayConversionTimeProperty() {
            return new IntProperty("StrayConversionTime");
        }

        public static IntProperty getStrayConversionTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "StrayConversionTime");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Stray
     */
    public static final class OfStray {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.WitherSkeleton
     */
    public static final class OfWitherSkeleton {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Blaze
     */
    public static final class OfBlaze {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "ExplosionRadius": BYTE
     *  - "Fuse": SHORT
     *  - "ignited": BOOLEAN
     *  - "powered": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Creeper
     */
    public static final class OfCreeper {

        public static ByteProperty createExplosionRadiusProperty() {
            return new ByteProperty("ExplosionRadius");
        }

        public static ByteProperty getExplosionRadiusProperty(Map<String, EntityProperty> map) {
            return g(map, "ExplosionRadius");
        }

        public static ShortProperty createFuseProperty() {
            return new ShortProperty("Fuse");
        }

        public static ShortProperty getFuseProperty(Map<String, EntityProperty> map) {
            return g(map, "Fuse");
        }

        public static BooleanProperty createIgnitedProperty() {
            return new BooleanProperty("ignited");
        }

        public static BooleanProperty getIgnitedProperty(Map<String, EntityProperty> map) {
            return g(map, "ignited");
        }

        public static BooleanProperty createPoweredProperty() {
            return new BooleanProperty("powered");
        }

        public static BooleanProperty getPoweredProperty(Map<String, EntityProperty> map) {
            return g(map, "powered");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties cannot be recognized yet:
     *  - "carriedBlockState": [COMPOUND]
     *
     * @see net.minecraft.world.entity.monster.EnderMan
     */
    public static final class OfEnderMan {

        public static UnsupportedProperty createCarriedBlockStateProperty() {
            return new UnsupportedProperty("carriedBlockState");
        }

        public static UnsupportedProperty getCarriedBlockStateProperty(Map<String, EntityProperty> map) {
            return g(map, "carriedBlockState");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Lifetime": INT
     *
     * @see net.minecraft.world.entity.monster.Endermite
     */
    public static final class OfEndermite {

        public static IntProperty createLifetimeProperty() {
            return new IntProperty("Lifetime");
        }

        public static IntProperty getLifetimeProperty(Map<String, EntityProperty> map) {
            return g(map, "Lifetime");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Giant
     */
    public static final class OfGiant {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Guardian
     */
    public static final class OfGuardian {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.ElderGuardian
     */
    public static final class OfElderGuardian {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "PatrolLeader": BOOLEAN
     *  - "Patrolling": BOOLEAN
     *  - "patrol_target": BLOCK_POS
     *
     * @see net.minecraft.world.entity.monster.PatrollingMonster
     */
    public static final class OfPatrollingMonster {

        public static BooleanProperty createPatrolLeaderProperty() {
            return new BooleanProperty("PatrolLeader");
        }

        public static BooleanProperty getPatrolLeaderProperty(Map<String, EntityProperty> map) {
            return g(map, "PatrolLeader");
        }

        public static BooleanProperty createPatrollingProperty() {
            return new BooleanProperty("Patrolling");
        }

        public static BooleanProperty getPatrollingProperty(Map<String, EntityProperty> map) {
            return g(map, "Patrolling");
        }

        public static BlockPosProperty createPatrolTargetProperty() {
            return new BlockPosProperty("patrol_target");
        }

        public static BlockPosProperty getPatrolTargetProperty(Map<String, EntityProperty> map) {
            return g(map, "patrol_target");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CanJoinRaid": BOOLEAN
     *  - "RaidId": INT
     *  - "Wave": INT
     *
     * @see net.minecraft.world.entity.raid.Raider
     */
    public static final class OfRaider {

        public static BooleanProperty createCanJoinRaidProperty() {
            return new BooleanProperty("CanJoinRaid");
        }

        public static BooleanProperty getCanJoinRaidProperty(Map<String, EntityProperty> map) {
            return g(map, "CanJoinRaid");
        }

        public static IntProperty createRaidIdProperty() {
            return new IntProperty("RaidId");
        }

        public static IntProperty getRaidIdProperty(Map<String, EntityProperty> map) {
            return g(map, "RaidId");
        }

        public static IntProperty createWaveProperty() {
            return new IntProperty("Wave");
        }

        public static IntProperty getWaveProperty(Map<String, EntityProperty> map) {
            return g(map, "Wave");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.AbstractIllager
     */
    public static final class OfAbstractIllager {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Pillager
     */
    public static final class OfPillager {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "SpellTicks": INT
     *
     * @see net.minecraft.world.entity.monster.SpellcasterIllager
     */
    public static final class OfSpellcasterIllager {

        public static IntProperty createSpellTicksProperty() {
            return new IntProperty("SpellTicks");
        }

        public static IntProperty getSpellTicksProperty(Map<String, EntityProperty> map) {
            return g(map, "SpellTicks");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Evoker
     */
    public static final class OfEvoker {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Illusioner
     */
    public static final class OfIllusioner {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Johnny": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Vindicator
     */
    public static final class OfVindicator {

        public static BooleanProperty createJohnnyProperty() {
            return new BooleanProperty("Johnny");
        }

        public static BooleanProperty getJohnnyProperty(Map<String, EntityProperty> map) {
            return g(map, "Johnny");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "AttackTick": INT
     *  - "RoarTick": INT
     *  - "StunTick": INT
     *
     * @see net.minecraft.world.entity.monster.Ravager
     */
    public static final class OfRavager {

        public static IntProperty createAttackTickProperty() {
            return new IntProperty("AttackTick");
        }

        public static IntProperty getAttackTickProperty(Map<String, EntityProperty> map) {
            return g(map, "AttackTick");
        }

        public static IntProperty createRoarTickProperty() {
            return new IntProperty("RoarTick");
        }

        public static IntProperty getRoarTickProperty(Map<String, EntityProperty> map) {
            return g(map, "RoarTick");
        }

        public static IntProperty createStunTickProperty() {
            return new IntProperty("StunTick");
        }

        public static IntProperty getStunTickProperty(Map<String, EntityProperty> map) {
            return g(map, "StunTick");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Witch
     */
    public static final class OfWitch {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Silverfish
     */
    public static final class OfSilverfish {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Spider
     */
    public static final class OfSpider {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.CaveSpider
     */
    public static final class OfCaveSpider {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "BoundX": INT
     *  - "BoundY": INT
     *  - "BoundZ": INT
     *  - "LifeTicks": INT
     *
     * @see net.minecraft.world.entity.monster.Vex
     */
    public static final class OfVex {

        public static IntProperty createBoundXProperty() {
            return new IntProperty("BoundX");
        }

        public static IntProperty getBoundXProperty(Map<String, EntityProperty> map) {
            return g(map, "BoundX");
        }

        public static IntProperty createBoundYProperty() {
            return new IntProperty("BoundY");
        }

        public static IntProperty getBoundYProperty(Map<String, EntityProperty> map) {
            return g(map, "BoundY");
        }

        public static IntProperty createBoundZProperty() {
            return new IntProperty("BoundZ");
        }

        public static IntProperty getBoundZProperty(Map<String, EntityProperty> map) {
            return g(map, "BoundZ");
        }

        public static IntProperty createLifeTicksProperty() {
            return new IntProperty("LifeTicks");
        }

        public static IntProperty getLifeTicksProperty(Map<String, EntityProperty> map) {
            return g(map, "LifeTicks");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "IsBaby": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Zoglin
     */
    public static final class OfZoglin {

        public static BooleanProperty createIsBabyProperty() {
            return new BooleanProperty("IsBaby");
        }

        public static BooleanProperty getIsBabyProperty(Map<String, EntityProperty> map) {
            return g(map, "IsBaby");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CanBreakDoors": BOOLEAN
     *  - "DrownedConversionTime": INT
     *  - "InWaterTime": INT
     *  - "IsBaby": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Zombie
     */
    public static final class OfZombie {

        public static BooleanProperty createCanBreakDoorsProperty() {
            return new BooleanProperty("CanBreakDoors");
        }

        public static BooleanProperty getCanBreakDoorsProperty(Map<String, EntityProperty> map) {
            return g(map, "CanBreakDoors");
        }

        public static IntProperty createDrownedConversionTimeProperty() {
            return new IntProperty("DrownedConversionTime");
        }

        public static IntProperty getDrownedConversionTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "DrownedConversionTime");
        }

        public static IntProperty createInWaterTimeProperty() {
            return new IntProperty("InWaterTime");
        }

        public static IntProperty getInWaterTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "InWaterTime");
        }

        public static BooleanProperty createIsBabyProperty() {
            return new BooleanProperty("IsBaby");
        }

        public static BooleanProperty getIsBabyProperty(Map<String, EntityProperty> map) {
            return g(map, "IsBaby");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Drowned
     */
    public static final class OfDrowned {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.Husk
     */
    public static final class OfHusk {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "ConversionPlayer": UUID
     *  - "ConversionTime": INT
     *  - "Xp": INT
     * [Attention] Some properties cannot be recognized yet:
     *  - "Gossips": [[COMPOUND]]
     *  - "Offers": [ANY]
     *  - "VillagerData": [COMPOUND]
     *
     * @see net.minecraft.world.entity.monster.ZombieVillager
     */
    public static final class OfZombieVillager {

        public static UuidProperty createConversionPlayerProperty() {
            return new UuidProperty("ConversionPlayer");
        }

        public static UuidProperty getConversionPlayerProperty(Map<String, EntityProperty> map) {
            return g(map, "ConversionPlayer");
        }

        public static IntProperty createConversionTimeProperty() {
            return new IntProperty("ConversionTime");
        }

        public static IntProperty getConversionTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "ConversionTime");
        }

        public static UnsupportedProperty createGossipsProperty() {
            return new UnsupportedProperty("Gossips");
        }

        public static UnsupportedProperty getGossipsProperty(Map<String, EntityProperty> map) {
            return g(map, "Gossips");
        }

        public static UnsupportedProperty createOffersProperty() {
            return new UnsupportedProperty("Offers");
        }

        public static UnsupportedProperty getOffersProperty(Map<String, EntityProperty> map) {
            return g(map, "Offers");
        }

        public static UnsupportedProperty createVillagerDataProperty() {
            return new UnsupportedProperty("VillagerData");
        }

        public static UnsupportedProperty getVillagerDataProperty(Map<String, EntityProperty> map) {
            return g(map, "VillagerData");
        }

        public static IntProperty createXpProperty() {
            return new IntProperty("Xp");
        }

        public static IntProperty getXpProperty(Map<String, EntityProperty> map) {
            return g(map, "Xp");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.ZombifiedPiglin
     */
    public static final class OfZombifiedPiglin {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.breeze.Breeze
     */
    public static final class OfBreeze {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "home_pos": BLOCK_POS
     *
     * @see net.minecraft.world.entity.monster.creaking.Creaking
     */
    public static final class OfCreaking {

        public static BlockPosProperty createHomePosProperty() {
            return new BlockPosProperty("home_pos");
        }

        public static BlockPosProperty getHomePosProperty(Map<String, EntityProperty> map) {
            return g(map, "home_pos");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "IsImmuneToZombification": BOOLEAN
     *  - "TimeInOverworld": INT
     *
     * @see net.minecraft.world.entity.monster.piglin.AbstractPiglin
     */
    public static final class OfAbstractPiglin {

        public static BooleanProperty createIsImmuneToZombificationProperty() {
            return new BooleanProperty("IsImmuneToZombification");
        }

        public static BooleanProperty getIsImmuneToZombificationProperty(Map<String, EntityProperty> map) {
            return g(map, "IsImmuneToZombification");
        }

        public static IntProperty createTimeInOverworldProperty() {
            return new IntProperty("TimeInOverworld");
        }

        public static IntProperty getTimeInOverworldProperty(Map<String, EntityProperty> map) {
            return g(map, "TimeInOverworld");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "CannotHunt": BOOLEAN
     *  - "IsBaby": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.piglin.Piglin
     */
    public static final class OfPiglin {

        public static BooleanProperty createCannotHuntProperty() {
            return new BooleanProperty("CannotHunt");
        }

        public static BooleanProperty getCannotHuntProperty(Map<String, EntityProperty> map) {
            return g(map, "CannotHunt");
        }

        public static BooleanProperty createIsBabyProperty() {
            return new BooleanProperty("IsBaby");
        }

        public static BooleanProperty getIsBabyProperty(Map<String, EntityProperty> map) {
            return g(map, "IsBaby");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.piglin.PiglinBrute
     */
    public static final class OfPiglinBrute {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     * [Attention] Some properties cannot be recognized yet:
     *  - "anger": [ANY]
     *  - "listener": [COMPOUND]
     *
     * @see net.minecraft.world.entity.monster.warden.Warden
     */
    public static final class OfWarden {

        public static UnsupportedProperty createAngerProperty() {
            return new UnsupportedProperty("anger");
        }

        public static UnsupportedProperty getAngerProperty(Map<String, EntityProperty> map) {
            return g(map, "anger");
        }

        public static UnsupportedProperty createListenerProperty() {
            return new UnsupportedProperty("listener");
        }

        public static UnsupportedProperty getListenerProperty(Map<String, EntityProperty> map) {
            return g(map, "listener");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.ambient.AmbientCreature
     */
    public static final class OfAmbientCreature {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "BatFlags": BYTE
     *
     * @see net.minecraft.world.entity.ambient.Bat
     */
    public static final class OfBat {

        public static ByteProperty createBatFlagsProperty() {
            return new ByteProperty("BatFlags");
        }

        public static ByteProperty getBatFlagsProperty(Map<String, EntityProperty> map) {
            return g(map, "BatFlags");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "DragonDeathTime": INT
     *  - "DragonPhase": INT
     *
     * @see net.minecraft.world.entity.boss.enderdragon.EnderDragon
     */
    public static final class OfEnderDragon {

        public static IntProperty createDragonDeathTimeProperty() {
            return new IntProperty("DragonDeathTime");
        }

        public static IntProperty getDragonDeathTimeProperty(Map<String, EntityProperty> map) {
            return g(map, "DragonDeathTime");
        }

        public static IntProperty createDragonPhaseProperty() {
            return new IntProperty("DragonPhase");
        }

        public static IntProperty getDragonPhaseProperty(Map<String, EntityProperty> map) {
            return g(map, "DragonPhase");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "Size": INT
     *  - "wasOnGround": BOOLEAN
     *
     * @see net.minecraft.world.entity.monster.Slime
     */
    public static final class OfSlime {

        public static IntProperty createSizeProperty() {
            return new IntProperty("Size");
        }

        public static IntProperty getSizeProperty(Map<String, EntityProperty> map) {
            return g(map, "Size");
        }

        public static BooleanProperty createWasOnGroundProperty() {
            return new BooleanProperty("wasOnGround");
        }

        public static BooleanProperty getWasOnGroundProperty(Map<String, EntityProperty> map) {
            return g(map, "wasOnGround");
        }
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *
     * @see net.minecraft.world.entity.monster.MagmaCube
     */
    public static final class OfMagmaCube {
    }

    /**
     * This class is automatically generated by a script.
     * Properties (NBT tags) of this entity:
     *  - "ArmorItems": [ITEM_STACK]
     *  - "Body": [FLOAT]
     *  - "DisabledSlots": INT
     *  - "HandItems": [ITEM_STACK]
     *  - "Head": [FLOAT]
     *  - "Invisible": BOOLEAN
     *  - "LeftArm": [FLOAT]
     *  - "LeftLeg": [FLOAT]
     *  - "Marker": BOOLEAN
     *  - "NoBasePlate": BOOLEAN
     *  - "RightArm": [FLOAT]
     *  - "RightLeg": [FLOAT]
     *  - "ShowArms": BOOLEAN
     *  - "Small": BOOLEAN
     * [Attention] Some properties cannot be recognized yet:
     *  - "Pose": [COMPOUND]
     *
     * @see net.minecraft.world.entity.decoration.ArmorStand
     */
    public static final class OfArmorStand {

        public static ItemStackListProperty createArmorItemsProperty() {
            return new ItemStackListProperty("ArmorItems");
        }

        public static ItemStackListProperty getArmorItemsProperty(Map<String, EntityProperty> map) {
            return g(map, "ArmorItems");
        }

        public static FloatListProperty createBodyProperty() {
            return new FloatListProperty("Body");
        }

        public static FloatListProperty getBodyProperty(Map<String, EntityProperty> map) {
            return g(map, "Body");
        }

        public static IntProperty createDisabledSlotsProperty() {
            return new IntProperty("DisabledSlots");
        }

        public static IntProperty getDisabledSlotsProperty(Map<String, EntityProperty> map) {
            return g(map, "DisabledSlots");
        }

        public static ItemStackListProperty createHandItemsProperty() {
            return new ItemStackListProperty("HandItems");
        }

        public static ItemStackListProperty getHandItemsProperty(Map<String, EntityProperty> map) {
            return g(map, "HandItems");
        }

        public static FloatListProperty createHeadProperty() {
            return new FloatListProperty("Head");
        }

        public static FloatListProperty getHeadProperty(Map<String, EntityProperty> map) {
            return g(map, "Head");
        }

        public static BooleanProperty createInvisibleProperty() {
            return new BooleanProperty("Invisible");
        }

        public static BooleanProperty getInvisibleProperty(Map<String, EntityProperty> map) {
            return g(map, "Invisible");
        }

        public static FloatListProperty createLeftArmProperty() {
            return new FloatListProperty("LeftArm");
        }

        public static FloatListProperty getLeftArmProperty(Map<String, EntityProperty> map) {
            return g(map, "LeftArm");
        }

        public static FloatListProperty createLeftLegProperty() {
            return new FloatListProperty("LeftLeg");
        }

        public static FloatListProperty getLeftLegProperty(Map<String, EntityProperty> map) {
            return g(map, "LeftLeg");
        }

        public static BooleanProperty createMarkerProperty() {
            return new BooleanProperty("Marker");
        }

        public static BooleanProperty getMarkerProperty(Map<String, EntityProperty> map) {
            return g(map, "Marker");
        }

        public static BooleanProperty createNoBasePlateProperty() {
            return new BooleanProperty("NoBasePlate");
        }

        public static BooleanProperty getNoBasePlateProperty(Map<String, EntityProperty> map) {
            return g(map, "NoBasePlate");
        }

        public static UnsupportedProperty createPoseProperty() {
            return new UnsupportedProperty("Pose");
        }

        public static UnsupportedProperty getPoseProperty(Map<String, EntityProperty> map) {
            return g(map, "Pose");
        }

        public static FloatListProperty createRightArmProperty() {
            return new FloatListProperty("RightArm");
        }

        public static FloatListProperty getRightArmProperty(Map<String, EntityProperty> map) {
            return g(map, "RightArm");
        }

        public static FloatListProperty createRightLegProperty() {
            return new FloatListProperty("RightLeg");
        }

        public static FloatListProperty getRightLegProperty(Map<String, EntityProperty> map) {
            return g(map, "RightLeg");
        }

        public static BooleanProperty createShowArmsProperty() {
            return new BooleanProperty("ShowArms");
        }

        public static BooleanProperty getShowArmsProperty(Map<String, EntityProperty> map) {
            return g(map, "ShowArms");
        }

        public static BooleanProperty createSmallProperty() {
            return new BooleanProperty("Small");
        }

        public static BooleanProperty getSmallProperty(Map<String, EntityProperty> map) {
            return g(map, "Small");
        }
    }

    @SuppressWarnings("unchecked")
    private static <T> T g(Map<String, EntityProperty> map, String key) {
        return (T) Optional.ofNullable(map.get(key)).orElseThrow(() -> new RuntimeException("Vanilla entity property \"" + key + "\" not found!"));
    }

    private static void p(Map<String, EntityProperty> map, EntityProperty... properties) {
        for (EntityProperty property : properties) {
            map.put(property.name(), property);
        }
    }
}
