modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "biologydictionary"
version = "${version}"
displayName = "Biology Dictionary"
authors = "XieNaoban"
description = '''
To display or modify the properties and states of mobs.
'''
#logoFile = ""

[[dependencies.biologydictionary]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biologydictionary]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biologydictionary]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "biologydictionary.mixins.json"
