package io.github.xienaoban.minecraft.biologydictionary.nbtparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.ImportDeclaration;
import com.github.javaparser.ast.Modifier;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.StringLiteralExpr;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import io.github.xienaoban.minecraft.biologydictionary.platform.util.JavaNames;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.entity.Entity;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

public final class AdditionalNbtMethodsVisitor extends VoidVisitorAdapter<Void> {
    private static final Logger LOGGER = LogManager.getLogger();

    public static final String PROPERTY_CLAZZ_NAME = "EntityVanillaProperty";
    public static final String PROPERTY_READ_METHOD_NAME = "readFrom";
    public static final String PROPERTY_WRITE_METHOD_NAME = "writeTo";
    public static final String TAG_ARG = "compoundTag";
    public static final String TARGET_TAG_ARG = "vanillaNbt";

    private final Class<? extends Entity> entityClazz;

    private final CompilationUnit sourceCompilationUnit;

    private final CompilationUnit targetCompilationUnit;
    private final ClassOrInterfaceDeclaration targetClazzDeclaration;
    private final File targetFilePath;

    private final Map<String /* property name */, ClassOrInterfaceDeclaration> propertyClazzDeclarations = new HashMap<>();
    private final Map<String /* property name */, MethodDeclaration          > propertyReadMethodDeclarations = new HashMap<>();
    private final Map<String /* property name */, MethodDeclaration          > propertyWriteMethodDeclarations = new HashMap<>();
    private final Map<String /* property name */, TagMap /* type */          > propertyNamesAndTypes = new HashMap<>();
    private final Map<String /* simple name */  , String /* full name */     > importedClazzes = new HashMap<>();

    public AdditionalNbtMethodsVisitor(Class<? extends Entity> entityClazz, String targetPackage, File targetDirPath) {
        String targetClazzSimpleName = entityClazz.getSimpleName() + "Properties";
        this.entityClazz = entityClazz;
        this.sourceCompilationUnit = AstParser.generateAst(entityClazz);
        this.targetCompilationUnit = new CompilationUnit(targetPackage);
        this.targetClazzDeclaration = targetCompilationUnit.addClass(targetClazzSimpleName, Modifier.Keyword.PUBLIC, Modifier.Keyword.FINAL);
        this.targetFilePath = Paths.get(targetDirPath.toString(), targetClazzSimpleName + ".java").toFile();
    }

    public void generate() {
        LOGGER.info("Start to generate properties of " + entityClazz.getName());
        try {
            parseAndGenerateAst();
        } finally {
            writeClassToFile();
        }
    }

    private void parseAndGenerateAst() {
        boolean good = false;
        try {
            visit(sourceCompilationUnit, null);
            good = true;
        } finally {
            renameTagArgName();
            targetCompilationUnit.addImport("io.github.xienaoban.minecraft.biologydictionary.api.EntityVanillaProperty");
            targetCompilationUnit.addImport(entityClazz);

            StringBuilder clazzComment = new StringBuilder("This class is automatically generated by the script. Please do not modify it.\n");
            clazzComment.append("Properties of this entity:\n");
            for (var entry : propertyNamesAndTypes.entrySet()) {
                clazzComment.append("  \"").append(entry.getKey()).append("\": ").append(entry.getValue().getType().getCanonicalName()).append('\n');
            }
            if (!good) {
                clazzComment.append("Something bad happened. Not only these properties...\n");
            }
            targetClazzDeclaration.setJavadocComment(clazzComment.toString());
        }
    }

    private void writeClassToFile() {
        // if (Files.isRegularFile(path)) return; // do not overwrite
        try (PrintWriter out = new PrintWriter(targetFilePath)) {
            out.print(targetCompilationUnit.toString());
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    public Class<? extends Entity> getEntityClazz() {
        return entityClazz;
    }

    public CompilationUnit getTargetCompilationUnit() {
        return targetCompilationUnit;
    }

    public ClassOrInterfaceDeclaration getTargetClazzDeclaration() {
        return targetClazzDeclaration;
    }

    public ClassOrInterfaceDeclaration getPropertyClazzDeclaration(String propertyName) {
        return propertyClazzDeclarations.computeIfAbsent(propertyName, s -> {
            ClassOrInterfaceDeclaration innerClazz = new ClassOrInterfaceDeclaration(
                    Modifier.createModifierList(Modifier.Keyword.PUBLIC, Modifier.Keyword.STATIC, Modifier.Keyword.FINAL),
                    false, s);
            targetClazzDeclaration.addMember(innerClazz);
            innerClazz.addImplementedType(PROPERTY_CLAZZ_NAME + "<" + entityClazz.getSimpleName() + ">");
            return innerClazz;
        });
    }

    public MethodDeclaration createPropertyReadMethodDeclaration(String propertyName) {
        if (propertyReadMethodDeclarations.containsKey(propertyName)) {
            throw new AssertionError("Parsed same property \"" + propertyName + "\" twice?!");
        }
        MethodDeclaration m = getPropertyClazzDeclaration(propertyName)
                .addMethod(PROPERTY_READ_METHOD_NAME, Modifier.Keyword.PUBLIC);
        m.addParameter(CompoundTag.class, TARGET_TAG_ARG);
        propertyReadMethodDeclarations.put(propertyName, m);
        return m;
    }

    public MethodDeclaration createPropertyWriteMethodDeclaration(String propertyName) {
        if (propertyWriteMethodDeclarations.containsKey(propertyName)) {
            throw new AssertionError("Parsed same property \"" + propertyName + "\" twice?!");
        }
        MethodDeclaration m = getPropertyClazzDeclaration(propertyName)
                .addMethod(PROPERTY_WRITE_METHOD_NAME, Modifier.Keyword.PUBLIC);
        m.addParameter(CompoundTag.class, TARGET_TAG_ARG);
        propertyWriteMethodDeclarations.put(propertyName, m);
        return m;
    }

    public void putPropertyNameAndType(MethodCallExpr n) {
        String methodName = n.getName().getIdentifier();
        boolean isGet = methodName.startsWith("get");
        boolean isPut = methodName.startsWith("put");
        if (isGet || isPut) {
            n.getScope().ifPresent(scopeExpr -> scopeExpr.ifNameExpr(nameExpr -> {
                String methodScope = nameExpr.getName().getIdentifier();
                if (TAG_ARG.equals(methodScope)) {
                    NodeList<Expression> arguments = n.getArguments();
                    if (isGet && arguments.size() != 1) {
                        if (!(arguments.size() == 2 && methodName.equals("getList"))) {
                            throw new AssertionError("Not compoundTag.getXXX: " + n);
                        }
                    }
                    if (isPut && arguments.size() != 2) {
                        throw new AssertionError("Not compoundTag.putXXX: " + n);
                    }
                    Expression first = arguments.get(0);
                    StringLiteralExpr stringLiteralExpr = first.asStringLiteralExpr();

                    String propertyName = stringLiteralExpr.getValue();
                    TagMap propertyType = TagMap.getByMethodGet(methodName);
                    TagMap propertyTypeOld = propertyNamesAndTypes.get(propertyName);
                    if (propertyTypeOld == null) propertyNamesAndTypes.put(propertyName, propertyType);
                    else if (propertyTypeOld != propertyType) {
                        throw new AssertionError("Different types of one property \"" + propertyName + "\": " + propertyTypeOld + " -> " + propertyType);
                    }
                }
            }));
        }
    }

    private void renameTagArgName() {
        targetClazzDeclaration.accept(new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(NameExpr n, Void arg) {
                super.visit(n, arg);
                if (AdditionalNbtMethodsVisitor.TAG_ARG.equals(n.getName().getIdentifier())) {
                    n.setName(TARGET_TAG_ARG);
                }
            }
        }, null);
    }

    @Override
    public void visit(ImportDeclaration n, Void arg) {
        super.visit(n, arg);
        if (n.isStatic()) throw new AssertionError("Let the decompiler do not generate static: \"" + n + "\".");
        if (n.isAsterisk()) throw new AssertionError("Let the decompiler do not generate asterisk: \"" + n + "\".");
        String name = n.getNameAsString();
        importedClazzes.put(name.substring(name.lastIndexOf('.') + 1), name);
        targetCompilationUnit.addImport(n);
    }

    @Override
    public void visit(MethodDeclaration md, Void arg) {
        super.visit(md, arg);
        final AbstractVisitorWrapper<Void> visitor;
        if (JavaNames.ENTITY_READ_ADDITIONAL_NBT.equals(md.getNameAsString())) {
            visitor = new ReadAdditionalNbtVisitor(this);
        } else if (JavaNames.ENTITY_WRITE_ADDITIONAL_NBT.equals(md.getNameAsString())) {
            return;
        } else return;

        BlockStmt blockStmt = md.getBody().orElseThrow(() -> new AssertionError("No body?!"));
        // new PrintNodeVisitor<>().visit(blockStmt, res);
        visitor.visit(blockStmt, null);
        visitor.end();
    }
}
